= Report on Roundtable VIII, 29 January - 2 February 2007
:docnumber: 0711
:copyright-year: 2006
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2007-02-02
:published-date: 2007-02-02
:technical-committee: CALCONNECT
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable VIII took place January 29 to February 2, 2007, hosted by Novell in Provo, Utah. The
event was attended by 30 representatives to the IOP testing and/or the Roundtable, including
representatives from two observers (organizations attending a Roundtable to see if they wish to
join).

Monday noon through Wednesday noon, January 29-31, was a dedicated CalConnect
Interoperability Test Event where participating organizations performed interoperability testing
between their calendaring and scheduling implementations. Wednesday afternoon, all day
Thursday, and Friday morning comprised the Roundtable. The majority of this time was dedicated
to technical committee sessions, BOFs, and informal discussions and networking, with an allhands
Plenary meeting as the last item on Friday morning. The Technical Committee sessions
were organized sequentially, to allow all attendees who wished to be involved in the discussions of
a Technical Committee the opportunity to do so.

== Update on Technical Committees and Initiatives

=== Work Products

Since Roundtable VII, TC USECASE has published the _Calendaring and
Scheduling Glossary of Terms_ and TC MOBILE has published _The Benefits of iCalendar for the
Mobile Industry_.

=== TC CALDAV

TC CALDAV and TC FREEBUSY jointly worked on the availability discussions
which contributed to the `VAVAILABILITY` specification recently submitted to the IETF by its
authors. The TC is in the final stages of work on the _CalDAV Scheduling Requirements_ paper
which should be published in February. Following completion of the paper, the TC plans work on
several topics including client metadata, external attachments, scheduled event updates,
synchronization support and polling improvements. TC CALDAV intends to complete its work by
Roundtable IX in May 2007, after which the TC will be shut down and TC REALTIME
reactivated.

=== TC EVENTPUB

TC EVENTPUB developed use cases and requirements for the `VVENUE`
iCalendar extension, which has been submitted to the IETF as an individual submission by its
authors. The TC is about to begin work on two new initiatives, event sharing and a possible event
sharing protocol for event servers, and localization and a possible `VLOCALIZE` iCalendar
extension.

=== TC FREEBUSY

The TC has completed its original scope of work with the completion of the
report to The Open Group. Following the Roundtable it will begin work on `FREEBUSY` URLs
and is exploring another initiative.

=== TC IOPTEST

TC IOPTEST conducted the IOP test event and is continuing to work with TC
MOBILE on the development of a Mobile Interoperability Test Suite and planning for a Mobile
Interoperability Test Event. The TC is planning to initiate monthly Jabber-based remote IOP test
events as an adjunct to the formal IOP test events conducted with the Roundtables.

=== TC MOBILE

The TC has completed and published _The Benefits of iCalendar for the Mobile
Industry_ and is working on the development of a Mobile Interoperability Test Suite in conjunction
with TC IOPTEST. Planning has begun for a Mobile Interoperability Test Event targeted to the
mobile device industry. Timing and location are not yet determined but late 3rd or 4th quarter in
Europe or the U.K. seem most likely at this time. The TC is also working on recurrence
simplification for mobile devices as input to the IETF CALSIFY effort.

=== TC REALTIME

The TC will be reactivated following the completion of the work in TC
CALDAV, which will free up some necessary resources; the Consortium's intent is to reactivate at
the May 2007 Roundtable. The TC anticipates focusing on three major discussion areas:
addressing, discovery, and authentication/authorization/access control, all of which are needed to
enable general server-server `freebusy` lookup and event scheduling.

=== TC USECASE

The TC has published the Calendaring and Scheduling Glossary of Terms and has
begun work on a paper defining usecases for the minimum interoperable subset for tasks (``VTODO``s).
The TC has also undertaken a study of recurrence features in mobile device support for TC
MOBILE, and is considering a work item on usecases for resource management.

=== Daylight Saving Time Ad Hoc

The DST Ad Hoc Group has developed and published on the
Consortium Website two documents having to do with the imminent DST change: _Extended
Daylight Saving Time Review and Considerations_ and _Extended Daylight Saving Time Links_,
_Advisories and Changes_. In early summer the group plans to develop and publish a "Lessons
Learned" from user experiences during March as a reference and guide to the change back to
standard time in November.

=== vCard Ad Hoc Group

There is still interest initiating work in the contacts/vCard area but it waits
on the availability of resources from existing or new members.

=== CalConnect Interoperability Test Event

Participants in the IOP test event
included Apple, Eventful, Kerio, Marware, Novell, Oracle, OSAF, and Bedework (Rensselaer
Polytechnic Institute). Results from the event will be posted at Past IOP Reports shortly.

=== BOFS

For the first time, the Roundtable was able to provide time for BOFS, and three were held,
on localization, the `freebusy` URL, and DST conversions. The Consortium plans to continue to
provide schedule time for BOFS in the future, together with informal networking amongst those
not interested in the BOFS.

=== New Initiatives

Work will be undertaken in existing TCS on new initiatives including
localization, the `FREEBUSY` URL proposal, event sharing, and other possible items which could
result in the establishment of new TCs once the subjects have been fleshed out and the work
scoped.

== Future Meetings

* ROUNDTABLE IX: May 7-11, Seattle, Washington, hosted by Boeing Aircraft Company.
* ROUNDTABLE X: September 17-21, Cambridge, Massachusetts, hosted by M.I.T. (location and
host tentative).
* ROUNDTABLE XI: February 4-8, 2008, location and host TBD
* ROUNDTABLE XII: June 2-6, 2008, Madison, Wisconsin, hosted by the University of
Wisconsin (date, location and host tentative).

The format of CalConnect week will remain the same for these events:

* Monday noon through Wednesday noon, IOP Test Event
* Wednesday noon through Friday noon, Roundtable (TC sessions, BOFs, networking, Plenary).
