= January 2005 CalConnect Interoperability Test Scenarios
:docnumber: 0501
:copyright-year: 2005
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2005-01-12
:published-date: 2005-01-12
:technical-committee: IOPTEST
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:


.Foreword

This document incorporates by reference the CalConnect Intellectual Property Rights,
Appropriate Usage, Trademarks and Disclaimer of Warranty for External (Public)
Documents as located at

http://www.calconnect.org/documents/disclaimerpublic.pdf.

== Basic Calendar Access Test Scenarios

=== Event creation

==== {blank}
Create new single-instance meeting titled "Meeting 1.1" with the location "Seattle".

[[cls-1.2]]
==== {blank}
Create new meeting titled "Meeting 1.2" recurring every Monday from 10:00 AM to 11:00
AM for 4 weeks.

==== {blank}
Create new single-instance meeting titled "Meeting 1.3" with 2 other attendees.

==== {blank}
Create new single-instance meeting titled "Meeting 1.4" with an alarm set to trigger
15 minutes prior to the schedule time of the meeting.

=== Event modification

==== {blank}
Modify the title of meeting "Meeting 1.1" to "Meeting 1.1bis".

==== {blank}
Modify the location of the meeting "Meeting 1.1bis" to "Seattle bis".

==== {blank}
Reschedule meeting "Meeting 1.1bis" to the next day.

==== {blank}
Add an attendee to "Meeting 1.1bis".

==== {blank}
Add an alarm to "Meeting 1.1bis".

==== {blank}
Modify the title of the 1st instance of the recurring meeting created in <<cls-1.2>>.

==== {blank}
Modify the participation status of

==== {blank}
Cancel the 4th instance of the recurring meeting created in <<cls-1.2>>.

==== {blank}
One client changes "Meeting 1.1bis" to a different time, second client 'refreshes' its display to see the modification.

=== Event retrieval

==== {blank}
Retrieve all the components and properties of the meetings scheduled for the current day (i.e., midnight to midnight local time).

==== {blank}
Retrieve all the components and properties of the meetings scheduled for the current week.

==== {blank}
Retrieve all the components and properties of the meetings scheduled for the current month.

==== {blank}
Retrieve only the SUMMARY, DTSTART and DTEND
(or DURATION) properties of the meetings scheduled for the current week.

=== Event deletion

==== {blank}
Delete the meeting titled "Meeting 1.1bis"

==== {blank}
Delete the meeting titles "Meeting 1.2"
