= CalConnect administrative documents

This repository contains CalConnect administrative document sources.

image:https://github.com/CalConnect/cc-admin-documents/workflows/docker/badge.svg["Docker Build Status", link="https://github.com/CalConnect/cc-admin-documents/actions/workflows/docker.yml"]

Published documents are available here:

* https://calconnect.github.io/cc-admin-documents/[CalConnect Conference and IOP Testing Reports]


== Purpose

This repository holds the Metanorma source markup for CalConnect
administrative documents.

These documents include:

* CalConnect Conference Reports (and associated documents)
* CalConnect IOP Testing Reports
* CalConnect Advisory Notices

NOTE: These administrative documents, prior to 2024, were published in PDF
format only. This repository contains the re-encoded documents in the Metanorma
format in order to facilitate future updates and publication in multiple
formats.


== Structure

The repository is structured as follows:

`metanorma.yml`:: Metanorma site manifest that lists the documents to be
included in the site.

`sources/`:: Source documents in Metanorma format.

`sources/cc-{docnumber}-{title}`:: Directory for each document, named by
document number and a shorthand title.

`sources/cc-{docnumber}-{title}/document.adoc`:: Metanorma root document for
the document.


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/cc-admin-documents/
----


== Installing build tools

See https://www.metanorma.org/install/


== Building the documents

=== Full set

Run the following command to build the full collection of the documents.

[source,sh]
----
$ bundle exec metanorma site generate --agree-to-terms
----

=== Single document

Run the following command to build a single document.

.Compile a single document
[source,sh]
----
$ bundle exec metanorma sources/cc-1903-report-conference-46/document.adoc
----

=== Outputs

The following outputs will be built:

Index of all documents:: `_site/index.html`

Individual document outputs:: `_site/documents/` (HTML, PDF, MN XML)


== License

Copyright CalConnect.
