= Report on Roundtable XXIX, February 5-7, 2014
:docnumber: 1401
:copyright-year: 2014
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2014-02-26
:published-date: 2014-02-26
:technical-committee: CALCONNECT
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable XXIX took place on February 5-7, 2014, hosted by Mozilla in San Francisco,
California. The Roundtable was attended by 31 people from 20 members and one first-time nonmember
observer. The CalConnect Interoperability Test Event was held immediately prior to the
Roundtable on February 3-5, and had 21 participants onsite from 11 members, plus two members
testing remotely. In total, 36 people attended some portion of the week, including two from Hong
Kong, one each from the Czech Republic, England, France, India, New Zealand and Switzerland,
and the remainder from North America.

The Roundtable consisted primarily of technical committee sessions, workshops and BOFs. In
addition new member presentations were offered during the Opening Session, as was a special
session dedicated to reviewing the ongoing work on restructuring the Steering Committee. The
sessions were as usual organized sequentially without competing parallel sessions, as is our
standard practice, to allow all attendees who wished to be involved in the discussions of each
Technical Committee the opportunity to do so. The Roundtable finished with the CalConnect
Plenary Session on Friday afternoon.

== Special Events

A BOF on CardDAV Sharing led to the formation of a new Provisional Committee (formerly Ad
Hoc) on Contacts Sharing to report out at CalConnect XXX in May.

A BOF on the iSchedule Domain Identifier led to agreement on a way forward with this
contentions issue which will be integrated into the work of TC ISCHEDULE.

== Documents since Last Roundtable

Much of the work in CalConnect is focused on specifications to become internet draft submissions to the IETF and
ultimately be progressed to become RFCs (Proposed Standards), rather than be directly published by CalConnect itself.

=== Published Documents

* Calendaring Service Architecture
* Task Architecture V0.4
* Report on Roundtable XXIX
* Report on Interoperability Test Event XXIX
* 7 Things You Should Know About Digital Travel Itineraries
* 7 Things You Should Know About Tasks

=== Updated internet drafts and published RFCs

* https://tools.ietf.org/html/rfc7095[jCard: The JSON Format for vCard] (RFC 7095)
* https://tools.ietf.org/html/draft-daboo-icalendar-rscale-02[Non-Gregorian Recurrence Rules in iCalendar]
* https://tools.ietf.org/html/draft-douglass-ical-relations/[Support for iCalendar Relationships]
* https://tools.ietf.org/html/draft-kewisch-et-al-icalendar-in-json/[jCal: The JSON format for iCalendar]
* https://datatracker.ietf.org/doc/rfc8144/[Use of the Prefer Header Field in Web Distributed Authoring and Versioning (WebDAV)]
* https://tools.ietf.org/html/draft-daboo-caldav-attachments/[CalDAV Managed Attachments]
* https://datatracker.ietf.org/doc/draft-daboo-icalendar-extensions/[New Properties for iCalendar]
* https://tools.ietf.org/html/draft-douglass-timezone-service-10[Timezone Service Protocol]
* https://www.ietf.org/internet-drafts/draft-daboo-calendar-%20availability-04.txt[Calendar Availability](VAVAILABILITY)
* https://www.ietf.org/internet-drafts/draft-douglass-calendar-%20extension-04.txt[Event Publishing Extensions to iCalendar]

== Update on Technical Committee Work and Initiatives Including BOFs and Workshops

=== API Ad Hoc

The API Ad Hoc Committee was formed at CalConnect XXVIII to evaluate a work area for
CalConnect on an Abstract API for Calendaring and Scheduling. The Ad Hoc recommended
forming a Technical Committee and had produced a draft charter, an outline of an abstract API
and some milestones, in addition to a draft Architecture for Calendaring and Scheduling.
Deliverables are expected to be a well specified abstract API and a simple instantiation of that API
-- probably some sort of RESTful web api. Instantiation of the follow-on TC will occur shortly
after the conference.

=== CALSCALE Ad Hoc

The draft was updated following CalConnect XXVIII:
https://tools.ietf.org/html/draft-daboo-icalendar-rscale-02[Non-Gregorian Recurrence Rules in iCalendar].
The Ad Hoc presented a short presentation was done of the RSCALE proposal and
draft to do recurrences in different calendar scales and to do arithmetic in these scales. The
primary requirement is to support non-Gregorian calendars while maintaining compatibility by
using Gregorian dates in the actual calendar entries. There are still some compatibility issues,
however one implementation has been done. The draft is moving forward at the IETF.

=== FSC (Federated Shared Calendars) Ad Hoc

The Ad Hoc continued the discussion of sharing and federated calendar sharing and alternative
models, and agreed to continue to move forward as an Ad Hoc pending identification of an agreed
common way forward.

=== Itinerary Ad Hoc

No session was held at the conference. The goal is to improve the user experience with itinerary
info from travel sites by extending iCalendar to incorporated needed information; however, we
need input from travel industry experts on what is needed. The Ad Hoc continues to look for
experts to inform the work.

=== TC AUTODISCOVERY

No TC session was held at this conference. The TC has produced an initial draft of a mechanism
for multiple service discovery via a single protocol for client setup and submitted to the IETF:
https://datatracker.ietf.org/doc/draft-daboo-aggregated-service-discovery/[Aggregated Service Discovery]. We are waiting for an opportunity to move this forward at the
IETF.

=== TC CALDAV

The TC described the latest changes in the `VALARM` Extensions draft and introduced a new
recurrence splitting topic which led to discussion on support for `RANGE` and on invitations
growing to unreasonable size. Additionally the latest changes to the managed attachments
specification were reviewed, and a discussion initiated on rich capabilities: there seems to be
enough interest to move forward with a spec.

=== TC EVENTPUB

Summarized the state of the 2 drafts that have been worked on with this TC,
https://tools.ietf.org/html/draft-douglass-calendar-extension/[Event Publication Extensions to iCalendar] and
https://tools.ietf.org/html/draft-daboo-icalendar-extensions[New Properties for iCalendar].
Apart from a couple of changes both
are essentially ready to move forward to Last Call, and we will be able to demonstrate the use of
the new properties at the next interoperability test event.

=== TC FREEBUSY

The TC reviewed
https://tools.ietf.org/html/draft-york-vpoll-00[VPOLL: Consensus Scheduling Component for iCalendar] and had a demo of a
prototype web client supporting `VPOLL`.

=== TC IOPTEST

Had a successful and well attended Interoperability Test Event featuring 13 organizations and 23
participants (2 remote). The test event will be reported on separately at
http://www.calconnect.org/eventreports.shtml#ioptestevents[CalConnect Interoperability Test Event Reports].

=== TC ISCHEDULE

TC ISCHEDULE offered a brief introduction to iSchedule and discussed the "identity crisis"
(domain identifier) BOF and the results, followed by a discussion on Webfinger. Also discussed
how to develop understanding of and interest in deploying iSchedule. The TC will begin work on
a "7 things" document for iSchedule.

=== TC PUSH

CalConnect XXIX was the first conference since TC PUSH was established. The TC presented its
charter and the initial work on requirements and a 7 Things document. Some Push basics and
optimizations were discussed, as was HTTP long poll as a simple push protocol that serves as a
specific example for the framework.

=== TC RESOURCE

The TC session focused on how to find the additional information required by attendees and
organizers on locations and resources in calendar data and concluded that using the new structured
properties that allow inclusion of a link to more information is the way to go. The use of
information via vCards was preferred and clients will need to be able to parse vCard data and
possibly cache it. Also identified a need for an extension of CalDAV to include a principal
property pointing to related CardDAV.

=== TC TASKS

TC TASKS reviewed the work since CalConnect XXVII on relationships and the relationships
draft, extensions related to `RELTYPE` and defined formal versions to be registered, abd ab the ad
hoc approach for namespace tokens for specific applications. Also looked at the Task Architecture
V0.4 diagram worked on since the last conference

=== TC TIMEZONE

The TC reviewed the current state of the
https://tools.ietf.org/html/draft-douglass-timezone-service-10[Timezone Service Protocol]
draft, which has had
moderate changes since the last meeting, and reported on the interoperability testing results. The
service protocol draft is ready to move forward to informal last call in the IETF.

== Plenary Decisions

The Contacts Sharing Provisional Committee was established. The API, FSC, and Itinerary Ad
Hocs continue to explore these areas of work.

The Plenary decided to change the term "Roundtable", used from CalConnect's inception for its
conference, to "CalConnect Conference" or "Conference". The term Ad Hoc (Committee) was
also changed to Provisional Committee. Going forward these terms will be used, although
historical documents and pages will not be changed.

The offer from Kerio to host the Winter, 2015 meeting in San Jose was accepted.

== Future Events

* CalConnect XXX: May 19-23, 2014, AOL, Dulles, Virginia
* CalConnect XXXI: Autumn, 2014, Europe (host, location, exact dates TBD)
* CalConnect XXXII: January 26-30, 2015, Kerio Technologies, San Jose, California

The general format of the CalConnect week is:

* Monday morning through Wednesday noon, CalConnect Interoperability Test Event
* Wednesday noon through Friday afternoon, CalConnect Roundtable (presentations, TC sessions,
BOFs, networking, Plenary)

The format for European events is to move TC sessions to the afternoon and offer symposia and
BOFs during Thursday and Friday mornings.
