== CalConnect I -- April, 2000

=== Introduction

On April 11 and 12, 2000, CalConnect Spring was held in Boston. It was graciously hosted by
MIT and chaired by Bob Mahoney.

==== Participants

The following companies and representatives were in attendance:

* Tom Ransdell, Lotus,
* Dan Gurney, Iris/Lotus,
* John Sun, iPlanet,
* Ki Wong, iPlanet,
* Katia Hage, Microsoft,
* Colin DuPlantis, Critical Path,
* Bob Mahoney, MIT,
* Paul Hill, MIT.

Pat Egen sat at home with a broken leg, and assisted (poorly) from the sidelines.

==== Products Tested

The following products and versions were tested:

* EventCenter Version 3.0 (Critical Path)
* Outlook 2000 and Outlook Express 5.0 (Microsoft)
* iPlanet - internal unreleased alpha version iCS 5.0, server and client (Netscape)
* Organizer (Lotus)

=== General Summary

First off, thanks to everyone for their efforts. There was consensus that all participants have a
lot of work to do, and that another testing event should be held in the fall. A west coast location
was suggested, although some interest was also expressed for New Orleans or San Antonio. All
participants felt that great progress would be made in the coming months.

Little interoperability has occurred so far. Repeating events and canceled events seem to be
causing problems. Parsers are working OK but the actual generation of the data objects is very
inconsistent.

Problems found with recurrence included the following:

* one vendor always generates and expects ``RRULE``s, but cannot handle ``RDATE``s.
* two vendors always generate ``RDATE``s and cannot currently handle ``RRULE``s.
* one vendor handles ``RRULE``s but cannot handle exceptions.

There was a brief discussion about redesigning recurrence. Some useful alternatives were
suggested but the developers also seemed to be willing to live with the current specification.
They did feel that word-smithing would help. This will be brought back to the list in more detail
for some review.

The biggest complaints are currently with iMIP and the MIME handling. "iMIP under-constrains
what may be emitted by a data source; this requires a client to handle every possible case" which
is perceived as a heavy burden by the developers.

Regarding MIME: "(multipart mixed vs. multipart alternative vs. text-alternative vs.attachments
...)" - the developers would be happier if there fewer options, or perhaps some stronger assertions
in the draft. This too will be put on the list.

There has been virtually no interoperability testing of alarms yet. There were some side issues
relating to alarms, which will be brought back to the list.

There has been virtually no testing of conformance with line lengths yet.

A number of minor problems with blank spaces, terminating lines, and MIME boundaries were
observed and are in the process of being fixed by the implementors.

No tester has fully implemented Journals. One vendor has the support in the parser but no
support in the front end, so they cannot be generated or displayed by the product. All of the
implementors indicate that supporting Journals is intended and that no obstacles are seen, they are
just lower on the priority list so far.

There has been no testing of signed or encrypted objects. This should be a major goal of the next
testing event.

Some progress is better than no progress. Look for additional activity on the list as we post some
of the items referenced above. CalConnect Fall will be announced later in the year.

Respectfully submitted,

Pat Egen and Bob Mahoney
