= Report on CalConnect Conference XXX, May 21-23, 2014
:docnumber: 1405
:copyright-year: 2014
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2014-06-09
:published-date: 2014-06-09
:technical-committee: CALCONNECT
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:imagesdir: images/conference-30

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

NOTE: Following CalConnect XXIX in February, the term "Roundtable" was replaced by "Conference"
or "CalConnect Conference".

CalConnect Conference XXX took place on February 5-7, 2014, hosted by AOL in Dulles,
Virginia. The CalConnect Conference was attended by 28 people from 12 members and 8 nonmembers
(observers). The CalConnect Interoperability Test Event was held immediately prior to
the Roundtable on February 3-5, and had 12 participants onsite from 8 members and one nonmember,
plus two members testing remotely. An additional 21 people from 8 organizations
attended the Wednesday workshop (see below) and did not attend any part of the Conference. In
total, 49 people from 29 organizations attended some portion of the week.

The Conference consisted primarily of technical committee sessions, workshops and BOFs. In
addition two live demonstrations of work under development were offered, as was a special
session reporting on the effort to restructure the CalConnect Steering Committee. The sessions
were as usual organized sequentially without competing parallel sessions, as is our standard
practice, to allow all attendees who wished to be involved in the discussions of each Technical
Committee the opportunity to do so. The Conference finished with the CalConnect Plenary
Session on Friday afternoon.

== Special Events

A public Workshop on the Veterans Administration Scheduling System Challenge was held
Wednesday afternoon and was attended by 47 people, 21 of whom came for the workshop alone.
Most Conference participants were present for the Workshop as well. A separate report on the
workshop can be found at
http://www.calconnect.org/vachallengeworkshopreport.shtml[VA Scheduling System Workshop Report].

A BoF on CalConnect and the IETF was held Thursday afternoon with the two Application Area
ADs from the IETF attending Thursday morning and through the BoF. The goal of the BoF was to
explore ways to better integrate IETF and CalConnect processes and allow for smoother
progression of drafts through the IETF once submitted. A formal liaison between the IETF and
CalConnect was suggested and will be explored.

== Documents since Last Roundtable

Much of the work in CalConnect is focused on specifications to become internet draft
submissions to the IETF and
ultimately be progressed to become RFCs (Proposed Standards), rather than be directly
published by CalConnect itself.

=== Published Documents

* Report on Roundtable XXIX
* Report on Interoperability Test Event XXIX
* 7 Things You Should Know About PUSH
* Starter List of CalDAV and CardDAV Standards and Specifications

=== Updated Internet Drafts and Published RFCs

* https://tools.ietf.org/html/rfc7265[jCal: The JSON Format for iCalendar] (RFC 7265)
* https://tools.ietf.org/html/draft-daboo-icalendar-rscale/[Non-Gregorian Recurrence Rules in iCalendar]
* https://tools.ietf.org/html/draft-daboo-caldav-attachments/[CalDAV Managed Attachments]
* https://datatracker.ietf.org/doc/draft-york-vpoll/[VPOLL: Consensus Scheduling Component for iCalendar]
* https://tools.ietf.org/html/draft-daboo-caldav-extensions[Collected Extensions to CalDAV]
* https://www.ietf.org/html/draft-daboo-caldav-timezone/[CalDAV: Timezones by Reference]

== Update on Technical Committee Work and Initiatives Including BOFs and Workshops

=== CALSCALE Ad Hoc

No session was held for the CALSCALE Ad Hoc as the draft is now pending progression at the
IETF. The draft was updated following CalConnect XXIX:
https://tools.ietf.org/html/draft-daboo-icalendar-rscale/[Non-Gregorian Recurrence Rules in iCalendar].
The Ad Hoc continues to explore ways of better explaining and documenting proper
RRULE RSCALE expansions for different non-Gregorian calendars.

=== CONTACTS Provisional Committee

The Contacts Sharing Provisional Committee demonstrated sharing models in use today including
Apple, BusyContacts, Fruux, Kerio and Zimbra. The current calendar sharing and notifications
draft specifications will be refactored into four or more focused specifications: Notification
framework, WebDAV collection sharing, CalDAV sharing, and CardDAV sharing. The Provisional
Committee will begin developing its Charter to become a Technical Committee.

=== FSC (Federated Shared Calendars) Ad Hoc

The Ad Hoc presented its work so far on calendars can be shared between different services and
users, and the points of intersection between the work of the Ad Hoc and the work begun in the
Contacts Sharing Provisional Committee. The draft Charter for the proposed TC FSC will be
circulated after the Conference and instantiation as a Technical Committee should happen next
month.

=== Itinerary Ad Hoc

No session was held at the conference. The goal is to improve the user experience with itinerary
info from travel sites by extending iCalendar to incorporated needed information; however, we
need input from travel industry experts on what is needed. The Ad Hoc continues to look for
experts to inform the work.

=== TC API

The TC discussed progress since the last Conference: a charter was developed and instantiation as
a Technical Committee was approved. The Technical Committee is making some progress on an
abstract API and believes it has a framework in which to work. The hardest issue to deal with
short-term is searching: we need to develop an abstract searching approach to provide much richer
capabilities than at present. The TC has begun work on a 7 Things document, somewhat
handicapped by the abstract nature of the topic and the work being done.

=== TC AUTODISCOVERY

No TC session was held at this conference. The TC has produced an initial draft of a mechanism
for multiple service discovery via a single protocol for client setup and submitted to the IETF:
https://datatracker.ietf.org/doc/draft-daboo-aggregated-service-%20discovery/[Aggregated Service Discovery].
We are waiting for an opportunity to move this forward at the IETF.

=== TC CALDAV

Several ongoing topics were presented and discussed, including

* Rich Capabilities - the basic outline was discussed. Current issues including backwards
compatibility with the DAV header and efficient change notification will be considered by
the TC.

* Storing encrypted data on a CalDAV server - input from the IETF was that it was important
to expose this work early, and the TC will look into creating a problem statement to take to
an appropriate IETF WAG.

* Draft Events - an outline of a possible solution was presented and discussed, but the feeling
was that the approach was overly complex; the TC will work on a more streamlined
approach.

* Group scheduling - a new topic from the interoperability test event earlier in the week.
Discussed how scheduling with groups and "self-invite" modes of scheduling could be
implemented in iCalendar and CardDAV; there is interest in the TC in working in this area.

* New issue in the meeting - possibility of defining a simple HTTP-based iTIP response
option so that web services can implement a simple request/response scheduling feature
without having to implement an e-mail service.

* REMOVED PARTSTAT - another issue from the interoperability testing, the addition of a
new REMOVED partstat to allow attendees (VPOLL) voters) to have themselves entirely
removed from an invite rather than just decline. This will probably be work on in TC
FREEBUSY.

=== TC EVENTPUB

TC EVENTPUB has not been active since shortly after the last Conference. We summarized the
state of the internet drafts (below) and are waiting for the first batch to progress. Some minor
modifications to the drafts may be required to handle issues raised in other TCs, especially
handling of referenced vCard data. The CONFERENCE property removed from one of the drafts
is now becoming of interest so we will have one or more EVENTPUB calls in the near future to
discuss adding it again. The current EVENTPUB drafts referenced above are
https://tools.ietf.org/html/draft-douglass-calendar-extension/[Event Publication Extensions to iCalendar]
and https://tools.ietf.org/html/draft-daboo-icalendar-extensions[New Properties for iCalendar].

=== TC FREEBUSY

The TC reviewed the draft specification:
https://tools.ietf.org/html/draft-york-vpoll-00[VPOLL: Consensus Scheduling Component for iCalendar].
Following the review a live demonstration was held of VPOLL via iSCHEDULE
between three implementations to show the technology and how it integrates different protocols.
The presentation was very well received especially by some of the observers from the Health Care
sector. We also discussed other ways of using VPOLL for bidding and assignments; a goal of the
TC going forward is to assemble use cases and develop alternative poll modes.

=== TC IOPTEST

The TC conducted a busy interoperability test event, with many basic CalDAV access issues
uncovered, and some fixed. Three servers tested and eventually demonstrated a combination of
VPOLL and iSCHEDULE (see the TC FREEBUSY entry above). The complete VPOLL and
subsequent meeting request sequence worked; there are still some issues with freebusy lookup.
Also conducted some testing go CalDAV scheduling and CardDAV sharing. The event report may
be found at
https://www.calconnect.org/events/event-reports#ioptestevents[CalConnect Interoperability Test Event Reports].

=== TC ISCHEDULE

TC ISCHEDULE offered a brief overview of the iSchedule protocol followed by a discussion of
what we have termed the "identify crisis" problem and the proposed solution that the TC has been
working on. (The "identify crisis" is how to determine the actual calendar user address of an
invitee when the invitation is being managed via iSchedule.) The proposed solution involve three
new pieces (as far as iSchedule is concerned): Webfinger, a "scheduleto" URI and a SCHEDULEADDRESS
parameter. Following up on this the TC will review the current proposal and work on
moving the iSchedule work into the IETF as soon as possible to that we can get feedback on the
identity issues from other technical areas and experts within the IETF.

=== TC PUSH

TC PUSH presented the recent work of the Technical Committee. The first piece has been a
schema to allow servers to advertise supported push transports. A brief introduction was done into
some of th existing push concepts for those not familiar with some of the terms and technologies.
The TC presented three different scenarios for push and how they differ when it comes to
subscribing to change notifications for a resource. It was pointed out that vendors are unlikely to
change their (existing) push implementation, and we discussed the concept of a push gateway that
abstracts from the actual push transport and provides a standardized push interface to application
servers.

=== TC RESOURCE

A presentation on the resource schema work so far was followed by a discussion of resource
schemas for building management, etc. We need to look at ways to integrate or provide APIs for
information relevant to the calendaring and scheduling world. Information in the structured
location draft as to how to provide it so it is always available for users. The TC is now waiting on
its drafts to be processed so will be dormant unless an issue comes up that must be addressed by
the TC.

=== TC TASKS

The TC presented its work to date and is currently refining its overall draft for enhancing task
scheduling in iCalendar. The main issue for discussion was how to track or maintain a history of
changes occurring in an iCalendar object, in particular changes to status information and info
added to iTIP replies for tasks. In particular, the question of where to employ inline data versus
pointers to external message streams, versioning, etc. must be addressed; the next few TC calls
will be devoted to this topic, and the TC is asking interested people to participate.

=== TC TIMEZONE

The TC has been largely dormant since the last Conference. We briefly summarized the state of
the draft Timezone Service Protocol and Timezones by Reference drafts. We also discussed an
issue raised on the IETF CALDAV list related to MS timezones and server handling of them when
implicit timezones are enabled. It may be time to start pushing idea of an IANA registry as part of
the IETF process. The relevant drafts are
https://www.ietf.org/html/draft-daboo-caldav-timezone/[Timezone Service Protocol and CalDAV: Timezones by Reference].

=== VA Workshop Follow-up

CalConnect extended its thanks to all who were invited and who participated. We will follow up
with more personal contacts, and will setting up short-lived mailing list for everyone who
attended. We learned that lots could be done in areas of scheduling and health care; our challenge
is to absorb expertise but the thing that will drive it is having a member or so in health care
industry (similar to DHL in tasks). We aren't ready to tackle the entire area but could cut out
tractable sections such as recurrences in prescription meds. Hopefully we will have a dialog and
one or more members with a business objective who see that CalConnect is where to realize that
objective.

== Plenary Decisions

The Federated Shared Calendars (FSC) Ad Hoc Committee and the CONTACTS Provisional
Committee will begin the process to establish themselves as full Technical Committees.

The offer from Youcanbook.me to host the Autumn 2014 event in Bedford, England was
confirmed.

== Future Events

* CalConnect XXXI: September 29 - October 3, 2014, Youcanbookme, Bedford, England
* CalConnect XXXII: January 26-30, 2015, Kerio Technologies, San Jose, California
* CalConnect XXXIII: Spring, 2015, TBD
* CalConnect XXXIV: Autumn, 2015, Amsterdam, The Netherlands (tentative)

The general format of the CalConnect week is:

* Monday morning through Wednesday noon, CalConnect Interoperability Test Event
* Wednesday noon through Friday afternoon, CalConnect Conference (presentations, TC sessions,
BOFs, networking, Plenary)
* The format for European events is to move TC sessions to the afternoon and offer symposia and
BOFs during Thursday and Friday mornings.
