= Report on Roundtable VI, 22-25 May 2006
:docnumber: 0614
:copyright-year: 2006
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2006-05-23
:published-date: 2006-05-23
:technical-committee: CALCONNECT
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable VI took place on May 22-25, 2006, hosted by IBM/Lotus in Cambridge,
Massachusetts. Monday May 22nd and Tuesday morning the 23rd were a dedicated CalConnect
Interoperability Event where participating organizations performed interoperability testing on their
calendaring and scheduling implementations.

Tuesday morning a pair of Practicums on iCalendar standards and on CalDAV were offered. The
Roundtable itself convened midday on Tuesday the 23rd and closed midday on Thursday the 25th.

Tuesday afternoon was dedicated to a Mobile Calendaring Workshop, sponsored by TC-MOBILE
(and replacing TC MOBILE's regular working session).

Wednesday, and part of Thursday morning, were dedicated to the other technical committee
sessions, with an all-hands Plenary meeting at the end. The Technical Committee sessions were
organized sequentially, to allow all attendees who wished to be involved in the discussions of a
Technical Committee the opportunity to do so.

== Update on Technical Committees and Initiatives

*Work Products*: Since Roundtable V, _Recurrence Problems and Recommendations_ document and
the _Timezone Registry and Service Recommendations_ have been published. The _Calendaring
Glossary_ should proceed to last call shortly, as should the _Mobile Calendaring Questionnaire
Results_ Document.

*TC-AUTHENTICATE* is monitoring discussion on the issues of http authentication leading up to
the IETF meeting in July.

*TC-CALDAV* is working on requirements for CalDAV Scheduling as input to the development of
the scheduling draft for CalDAV.

*TC-EVENTPUB* has developed a proposal for a VVENUE extension to iCalendar to support
event publication with expanded information, and plans to submit it as an individual draft to the
IETF.

*TC-FREEBUSY* was formed at this Roundtable to coordinate CalConnect efforts associated with
The Open Group Federated Free/Busy Challenge, leading to a proof of concept demonstration in
Mid-July.

*TC-MOBILE* conducted its Mobile Calendaring Workshop at this Roundtable and will publish
the results of its mobile calendaring questionnaire shortly. The TC is beginning work on a white
paper delineating the reasons for (especially) mobile device and software manufacturers and
operators to migrate to iCalendar from vCalendar.

*TC-REALTIME* is actively working on the issues associated with server to server
communication.

*TC-RECURR* was disbanded, having completed its charter.

*TC-TIMEZONE* was disbanded, having completed its charter.

*TC-USECASE* has completed work on the Calendaring Glossary document, which will go to Last
Call in the Consortium shortly, and has begun work on the minimum interoperable subset for tasks
(vtodos).

*CalATOM Ad Hoc Group*: A discussion mailing list on CalATOM and associated issues such as
RSS was formed at this Roundtable. The discussion list is open to interested individuals whether
or not they represent CalConnect members.

*CalConnect Interoperability Event*: Participants in the interoperability testing event included
EVDB, Oracle, OSAF and RPI (Rensselaer Polytechnic Institute). Results from the event will be
posted at Past IOP Reports.

== Future Meetings

The next meeting (Roundtable VII) will take place 26-29 September 2006 in the San Francisco
Bay Area. The following meeting (Roundtable VIII) will take place in mid-January, probably on
the East Coast.
