= Report on CalConnect vCard Workshop, September 18 2007
:docnumber: 0714
:copyright-year: 2007
:language: en
:doctype: administrative
:edition: 1.1
:status: published
:revdate: 2007-09-18
:published-date: 2007-09-18
:technical-committee: VCARD WKSP
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:


.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

NOTE: Update 13-Nov-2007: The Draft Charter for the CalConnect vCard Technical Committee
has been added at the bottom of this web page.

CalConnect sponsored a open one-day workshop on vCard and what to do about it. The
event was held September 18, 2007 at the Massachusetts Institute of Technology in
Cambridge, Massachusetts. Registered attendance was about 20, but a few others sat in
during some portion of the day. About 3/4 of the attendees were from CalConnect
members, although not always a CalConnect representative from that member.

== Meeting Summary

The preliminary agenda is available at Prelminary Workshop Agenda. The workshop began
with a welcome and introduction by Dave Thewlis, the Executive Director of CalConnect,
who gave a brief overview of CalConnect, its relationship with the IETF, and how
CalConnect got involved with vCard in the first place. (Summary: as soon as you start to do
calendaring you get involved in address books and vCard pops up.) CalConnect members
have expressed for some time that "something ought to be done about vCard" but
CalConnect has not to this point had the resources to do anything, nor clarity on what ought
to be done and what if anything should be undertaken by CalConnect. The goal of this
workshop therefore was to see if there was general agreement on what the problems were,
and what should be undertaken by the IETF. Then as an ancillary, what should additionally
be undertaken by another entity (such as CalConnect) and is CalConnect the right place.

Cyrus Daboo of Apple provided an overview presentation of the problem and related
issues, which included a summarization of the 25 or so responses to the CalConnect
questionnaire on vCard issues. vCard Problems and Related Issues. This was followed by
a http://www.openmobilealliance.org/ftp/Public_documents/DS/DS_DO/2007/OMA-DS-DS_DO-2007-0002R01-INP_vCard_workshop.zip[presentation from the OMA DS]
discussing vCard and OMA DS (formerly SyncML) issues,
and a brief discussion on other related work or standards in other bodies.

The group then conducted a considerable discussion of vCard problems, what needed to
be fixed, and what should be done if a vCard revision was undertaken. There was
considerable agreement that a new specification should have the name changed, possibly
to "iCard". The final list of identified items is at List of Desired Elements for a vCard
Revision

A key point was that if a vCard revision happens, the resultant specification needs to be
significant enough and offer enough new things to make the business case for converting
to it to the many organizations which support vCard today (most of which haven't even
gone to vCard 3 yet). Related to that is that promotion, publicity, use cases and
requirements, and interoperability testing need to happen in parallel with the actual
specification revision.

The workshop discussed briefly whether the right thing to do was to scrap vCard and
develop an entirely new specification, but the consensus was that while that might be the
"right" thing to do from a theoretical viewpoint, it was probably not practical. On the other
hand, as noted above we need to avoid simply tackling the easy bits because nobody will
adopt what amounts to a minor revision - after all they didn't do so the last time.

Chris Newman, IETF Area Director, stated that the amount of interest (and concern) had
convinced him that the work should go forward in the IETF to revise vCard, and that he had
possible candidates for document editors and co-chairs for a working group, so he intended
to initiate the process of charter development.

Discussion on what needed to be done to provide input to the working group included use
cases, requirements, results of interoperability testing to determine minimum interoperable
subsets, etc., in addition to ultimately promoting the resultant specification. The first part of
this needs to happen quickly, if possible no later than the March 2008 IETF meeting to
provide something for the working group to start with. Discussion of possible venues for the
work did not identify any significant alternatives to CalConnect presuming that CalConnect
can undertake the work. The topic of allowing non-member-representatives to participate in
the CalConnect work was discussed briefly without any final decisions; however
CalConnect is in the process of adopting mechanisms to allow external public review and
comment on selected work items and does have some other ways in which this could be
enabled on a case-by-case basis (primarily the ability to include identified "industry experts"
not from CalConnect members in the deliberations of a TC).

From the CalConnect perspective, undertaking the work requires new resources; the
available technical resources are committed to existing Technical Committees. However,
several non-members have indicated that they are interested enough in the work to
consider joining CalConnect in order to participate.

CalConnect will develop a draft charter for a vCard Technical Committee, which will identify
the scope of the work, expected work products and timelines, and will do so on the public
vcard-workshop-l mailing list which was set up to complement the vCard Workshop. This
will allow all interested parties, by joining that list if they are not already subscribed, to be
informed on what is being proposed and develop a clearer understanding of what their
commitment might be if they decide to participate in the work. CalConnect expects that the
development of this charter and solicitation of volunteers to help will take several weeks.
The CalConnect TC CHAIRS and Steering Committee will then make a final decision on
whether to undertake the work based on the availability of the necessary resources.

== Other Notes

CalConnect had planned to offer an Internet audio stream together with a jabber room to
allow comments and to ask questions. However although several people indicated interest,
repeated emails prior to the workshop didn't elicit anyone saying they would use the facility,
so we did not set it up.

CalConnect thanks all of the participants in the workshop and everyone who worked to
make it a success.

== Workshop Presentations and Materials

* Workshop Preliminary Agenda
* Summary and Notes (text from this page)
* vCard Problems and Related Issues
* http://www.openmobilealliance.org/ftp/Public_documents/DS/DS_DO/2007/OMA-DS-DS_DO-2007-0002R01-INP_vCard_workshop.zip[OMA DS Presentation]
* List of Desired Elements for a vCard Revision

== Draft Charter for CalConnect vCard Technical Committee (as of 05-Oct-2007)

TC-VCard will provide support to the IETF vCard revision efforts by:

. Determining specific problem areas in the current vCard specifications that need to be
fixed. As input the TC will start with issues documented in the vCard workshop.
. Looking at enhancements to the specifications to address current needs.
. Working on interoperability test cases to expose these problems and to provide a means
to verify when they are fixed in the updated specifications.
. Work on an XML-syntax for a 1-to-1 mapping with vCard.

The technical committee will produce a recommendations document to the IETF describing
the suggested fixes and enhancements felt necessary.

The technical committee will work with other Calconnect technical committees to
accomplish this work (e.g., TC-Mobile, TC-XML (proposed), TC-Eventpub (VVENUE
overlap), TC-Ioptest (interoperability testing).

The technical committee will work on a "benefits" document to promote the new standard. It
will also help promote this amoungst vendors to try and encourage rapid deployment of the
new standard.

Mirroring the consensus of the vCard workshop, this TC does not plan to examine a
wholesale replacement of vCard.

Milestones:

* Nov 2007 TC Setup
* Jan 2008 Interoperability test cases.
* Feb 2008 Interoperability event.
* Feb 2008 Draft of recommendations.
* Mar 2008 Initial presentation to IETF.
* Jun 2008 Interoperability event.
* Jun 2008 Publish recommendations.
* Jul 2008 Final presentation to IETF
* Oct 2008 Interoperability event.
* Oct 2008 Publish XML mapping document.
* Oct 2008 Publish benefits document.
* Oct 2008 Shutdown.

NOTE: Comments and suggestions on this Draft Charter should be posted on the
vcard-workshop-l mailing list.
