= Report on Roundtable XVII, February 3-5 2010
:docnumber: 1001
:copyright-year: 2010
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2010-02-10
:published-date: 2010-02-10
:technical-committee: CHAIRS
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable XVII took place on February 3-5 2010, hosted by the University of California at
Irvine in Irvine, California. The event was attended by 26 people from 18 members. The
CalConnect Interoperability Test Event (CITE) was held immediately prior to the Roundtable on
February 1-3. Six members and 9 people participated in the regular test event, performing
interoperability testing between their calendaring and scheduling implementations. For the first
time, remote testing was usefully employed with three people and two servers located remotely,
including two client testers in another country, communicating via the Consortium's internal
secure jabber environment. A report on the CITE will be published as soon as information has
been delivered from all participants.

The Roundtable was dedicated to technical committee sessions, and informal discussions and
networking, with an all-hands Plenary meeting as the last item on Friday afternoon. The Technical
Committee sessions were as usual organized sequentially, without competing parallel sessions, as
is our standard practice to allow all attendees who wished to be involved in the discussions of each
Technical Committee the opportunity to do so.

== Special Events

A presentation on UC Irvine's (the host's) calendaring environment was presented as the first of a
regular User SIG (Special Interest Group) Profile when a customer organization hosts CalConnect.

== Update on Technical Committees and Initiatives

=== TC CALDAV

TC CALDAV acknowledged the publication of RFC 5545 (iTIP) and provided a
status update on Internet Drafts relevant to CalDAV. Open discussions on CalDAV extensions
scheduling, WebDAV synchronization, calendar attachments. Discussed the upcoming Internet-
Draft on new iCalendar properties.

=== TC EVENTPUB

TC EVENTPUB was reactivated with a revised charter. The TC has been
reviewing event publication use cases and how to deal with non-standard data, and has reached
consensus on the previously-proposed "Reference" property; an RFC will be developed and
submitted before the next Roundtable. The TC also discussed "dirty" (i.e. non-iCalendarcompliant)
data and how to deal with it, and raised the issue of a Certification program and multilanguage
support in VEVENTS.

=== TC FREEBUSY

TC FREEBUSY has continued discussions on consensus or poll scheduling and
is considering a possible iCalendar extension for VPOLL. CalDAV and iSchedule implications
and how VPOLL items would be stored on a server were also discussed.

=== TC IOPTEST

TC IOPTEST reported on the IOP test event just completed (elsewhere in this
report). Substantial iSchedule testing is expected

=== TC iSCHEDULE

TC iSCHEDULE presented an overview of the first iSchedule Internet Draft.
An approach to allow an iSchedule Receiver to test the authorization of an iSchedule Sender was
discussed. Discussion began on planning for iSchedule interoperability testing in May.

=== TC MOBILE

TC MOBILE discussed holding a Mobile Calendaring Interoperability Test Event
in conjunction with the May IOP test event, as sufficient interest was not shown prior to this event.
This test event would be focused on sync technologies, primarily ActiveSync. General sync
technology problems and issues were discussed including a detailed presentation by MailSite. The
consensus was to push forward with the May ActiveSync-focused test event, trying to get key
participants in place within a month or two.

=== TC RESOURCE

TC RESOURCE revised the existing draft and discussed open issues; some
attributes need better definition and better examples. Discussed whether it make sense to add
attributes that depend on the policy decisions of a deployment, and how to best define it or to get
information. Expect to begin CalConnect Last Call on the resource draft soon, followed by
submission to the IETF as an RFC.

=== TC TIMEZONE

TC TIMEZONE summarized the problems they are currently trying to solve
and gave a brief description of where the draft RFCs stand. The two major issues outstanding were
discussed: Timezone identifier format and the implications of Mr. Olson's retirement on the supply
of Timezone data.

=== TC USECASE

TC USECASE discussed the Glossary revision, RFC 3283 (Guide to Internet
Calendaring), and "NINE" (Non-Institutional / Non-Enterprise) usecases. A proposal was agreed
to remove the current link to the glossary, initiate a wiki page with updated state, and continue
discussions about a broader wiki. TC USECASE will work on the wiki glossary, then move it to
HTML format, then look at RFC 3282 in a broader picture with more than one target audience; it
is not clear what can be done about RFC 3283 if we wish to supersede it with a CalConnect
document or (more likely) a more dynamic alternative such as a wiki feed. TC USECASE will
also continue work on NINE usecases to publish a document useful for information and outreach.

=== TC XML

TC XML briefly discussed the status of the XML iCalendar Representation and is
working on an updated draft with additional samples, and a resource linking proposal. The
majority of the session was spent on design issues for the calendar web services specification;
feedback from the participants was helpful in narrowing down the scope of the initial
specification. TC XML will plan on producing an initial draft and publishing it by the May
Roundtable. This work together with the XML iCalendar Representation will be input to work by
the OASIS WS-Calendar committee to be formed later this month, and substantial collaborative
effort between the technical committees is expected.

== CalConnect Interoperability Test Event

Participants in the IOP test event included Apple, PeopleCube and Sun Microsystems. In addition,
EMClient (Icewarp) tested remotely and Oracle and Andrew McMillan (DaviCal) made their
servers remotely available for testing. Results from the event will be posted at Past IOP Reports as
soon as they are collated and prepared.

== Other News from Roundtable XVII

CalConnect's first European CalConnect week will be hosted by Kerio Technologies in Plzen,
Czech Republic, in the Autumn of 2011 - the latter half of September or early in October. SWAMI
(The Swedish Organization for Middleware Infrastructure) has offered to host a Meet CalConnect
introductory half-day for prospective members in Scandinavia the week before or after the
CalConnect week.

CalConnect has implemented the Calendar Developer mailing list as announced in October. The
list now has several dozen subscribers and is beginning to see activity.

CalConnect has established an internal Jabber service requiring a userid on the CalConnect
system, as a secure tool for remote IOP testing, TC meetings, etc.

== Future Events

* CALCONNECT XVIII: May 24-28, 2010, Carnegie Mellon University, Pittsburgh PA
* CALCONNECT XIX: October 4-8 2010, IBM/Lotus, Littleton MA
* CALCONNECT XX: January 31 - February 4, 2011, TBD.

The format of the CalConnect week is:

* Monday morning through Wednesday noon, C.I.T.E. (CalConnect Interoperability Test Event)
* Wednesday noon through Friday afternoon, Roundtable (presentations, TC sessions, BOFs,
networking, Plenary).
