= Report on Interoperability Test Event XXXIV, Sep 28-30, 2015
:docnumber: 1505
:copyright-year: 2015
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2015-10-19
:published-date: 2015-10-19
:technical-committee: CHAIRS
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Report

The September 2015 Calendar Interoperability event took place in Amsterdam, Netherlands
hosted by Gershon Janssen.

There were 9 members participating onsite represented by 12 individuals. Participating entities
were:

* 1&1 (the hosts)
* Apple
* Mozilla
* Oracle
* Spherical Cow Group (Bedework)
* SmoothSync
* Stylite
* YouCanBook.me
* Zimbra

Additionally present were Gershon Janssen, the host, and as ever Dave Thewlis, Executive
Director.

There was the usual testing of CalDAV as a number of participants continue to implement features
of that protocol. There were a number of client implementations at the event which allowed for
fairly extensive testng.

In addition to the usual testing of protocols we had other items which occupied our time:

There was a lot of interest in the new WebDAV server info document
(https://tools.ietf.org/html/draft-douglass-server-info). This allows clients to determine what
features are available from a service and to cache the information. It allows us to reduce the
number of headers being transferred and also allows for more complex information and a way for
servers to indicate the feature set has changed. We had implementations from 3 servers and 2
clients - all done during the meeting. The specification went through a number of rapid iterations
as we built the code.

We had planned for some work on the Apple CalDAV test suite to try to improve its usability in
continuous testing environments. Ralf Becker of Stylite developed at the meeting a php tool which
creates a SQLite database of test results and also provides a number of querying options. This
work will probably continue between meetings and we will revisit it at the next event.

There were a number of discussions that took place during the event. For previous sessions we had
tried to move these discussions to a separate room away from the main testing venue. However,
we have come to realize that these discussions are of some interest to all participants and that they
often provide unexpected insights. For the near future at least we will probably have these
discussions as part of the main event. Topics covered the server information document, the new
devguide work and possible extensions.

Once again, this has been a useful event for the participants. Our thanks go to Gershon Janssen for
hosting the event and his attentiveness during the testing.

Mike Douglass, Spherical Cow Group, CalConnect Interoperability Test Manager
