= Report on Roundtable XXIV, May 23-25, 2012
:docnumber: 1203
:copyright-year: 2012
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2012-06-01
:published-date: 2012-06-01
:technical-committee: CHAIRS
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable XXIV took place on May 23-25, 2012, hosted by Patricia Egen Consulting in
Chattanooga, Tennessee. The event was attended by 17 people from 11 organizations. The
CalConnect Interoperability Test Event was held immediately prior to the Roundtable on May 21-
23. Nine people from 4 organizations were present onsite, and one individual and implementation
participated remotely.

The Roundtable was dedicated to technical committee sessions, and informal discussions and
networking, with an all-hands Plenary meeting as the last item on Friday afternoon. The Technical
Committee sessions were as usual organized sequentially, without competing parallel sessions, as
is our standard practice to allow all attendees who wished to be involved in the discussions of each
Technical Committee the opportunity to do so.

== Special Events

Two "implementation" BOFS were planned to be held during the Interoperability Test Event on
Monday afternoon:

* CalDAV Test Suites and Performance Testing
* Shared Address Books

In the even the CalDAV Test Suites and Performance Testing BOF was held on Thursday
afternoon due to lack of time.

A special BOF on Autodiscovery was also held Wednesday afternoon as a follow-on to BOFs in
February and last October, and it was decided to form a Technical Committee to work in this area.

== Documents since Last Roundtable

Public Review Documents:

* CalWS-SOAP SOAP Web Services Protocol for Calendaring

Updated IETF Drafts and Proposed Standards related to CalConnect (includes updates to
published CalConnect documents):

* https://tools.ietf.org/html/draft-desruisseaux-caldav-sched-12
* https://www.ietf.org/rfc/rfc6578.txt
* https://datatracker.ietf.org/doc/draft-cal-resource-vcard/
* http://tools.ietf.org/html/draft-douglass-timezone-service/

CalConnect has replaced the internal Interoperability Test Event Report with an internal wiki, and
the public Interoperability Test Report with a section on the Test Event in the CalConnect _Minutes_
newsletter publised after each event.

== Update on Technical Committee Work and Initiatives

Roundtable session summaries and activities and a report on the Interoperability Test Event will
be available as part of the CalConnect _Minutes_ newsletter to be published shortly. Once it is
available this entry will be changed to link to the newsletter.

== Future Events

* CalConnect XXV: October 1-5, 2012, Google, Zurich, Switzerland
* CalConnect XXVI: January 28 - February 1, 2013, Oracle, San Francisco Bay Area, California
* CalConnect XXVII: June 3-7, 2012, University of Wisconsin, Madison, Wisconsin

The general format of the CalConnect week is:

* Monday morning through Wednesday noon, CalConnect Interoperability Test Event
* Wednesday noon through Friday afternoon, CalConnect Roundtable (presentations, TC sessions,
BOFs, networking, Plenary)
