= Report on Roundtable XI, February 6-8 2008
:docnumber: 0809
:copyright-year: 2008
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2008-02-08
:published-date: 2008-02-08
:technical-committee: CHAIRS
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable XI and the accompanying IOP Test Events took place February 6-8, 2008, hosted by
Sun Microsystems in Menlo Park, California. The event was attended by 53 representatives from
25 organizations, including representatives from five observers (organizations attending a
Roundtable to see if they wish to join). Two media representatives were also present by invitation
to see the Technology Preview on Wednesday afternoon.

The CalConnect Interoperability Test Events (C.I.T.E.) were held immediately prior to the
Roundtable, running all day Monday and Tuesday, February 4-5. Nine organizations participated
in the regular IOP Test Event, performing interoperability testing between their calendaring and
scheduling implementations. In parallel, CalConnect hosted its first Mobile Interoperability Test
Event, attended by three organizations interested in conducting mobile calendaring tests. A total of
30 people attended the two IOP Test Events, including four observers. Reports on the IOP Test
Events will be published as soon as possible.

Roundtable XI began Wednesday morning, and ran through early afternoon on Friday. Special
events at Roundtable XI included

* A Technology Preview demonstrating live interoperability in the areas of CalDAV
Scheduling, Server-Server, and Free/Busy URL. A presentation about this Technology
Preview is available at Roundtable XI Technology Preview.
* Presentations on the Danish eKalendar.dk project from representatives of the Danish
Government and of Cabo Communications, the prime contractor on the project. The
presentations are available at Danish eKalendar Project and eKalendar from a Developer's
Perspective.

The remainder of the Roundtable was dedicated to technical committee sessions, BOFs, and
informal discussions and networking, with an all-hands Plenary meeting as the last item on Friday
afternoon. The Technical Committee sessions were as usual organized sequentially, without
competing parallel sessions, to allow all attendees who wished to be involved in the discussions of
a Technical Committee the opportunity to do so.

== Update on Technical Committees and Initiatives

=== TC CALDAV

TC CALDAV reported on its work since the last Roundtable and on its planto
incorporate implicit scheduling into the CalDAV Scheduling Specification. Discussions were held
in this area to clarify specific elements of implicit scheduling for the Technical Committee.

=== TC EVENTPUB

TC EVENTPUB reviewed the current state of the VVENUE proposal and
initiated a discussion on whether the approach was correct, or whether we should be encuraging
the appropriate extensions to vCARD now that the IETF has undertaken a Working Group to
revise the vCard RFC.

=== TC FREEBUSY

TC FREEBUSY reviewed work since the last Roundtable, especially work on
Free/Busy URL and in preparing for the Technology Previews of CalDAV Scheduling, serverserver,
and Free/Busy URL and discussed synergies with the Danish Government and the
eKalender.dk project.

=== TC IOPTEST

TC IOPTEST reported on the IOP test events just completed, including the first
Mobile Interoperability Test Event, discussed early plans to implement an issue-tracking
mechanism, and decided to adopt a work item on a formal test suite and capabilities to support
virtual IOP testing.

=== TC MOBILE

TC MOBILE presented its work since the publication of the Mobile Calendar
Interoperability Test Suite, and discussed the first Mobile Calendar Interoperability Test Event just
completed. Future directions in work for extending the test suite for vCard testing, and a focus on
mobile requirements for CalDAV, were adopted into the work plan. TC MOBILE is also exploring
having the next Mobile Interoperability Test Event in Europe, possibly in the autumn of 2008.

=== TC REALTIME

TC REALTIME presented and discussed its work on the REALTIME
messaging protocol, Discovery, and Authentication and Authorization, and in particular needs for
additional expertise in security within CalConnect to inform this work.

=== TC TIMEZONE

TC TIMEZONE presented the conceptual work to date for the registry and
service proposals and led discussion on various elements of the proposals.

=== TC USECASE

The TC presented its in-progress work on Resources generating a lengthy
discussion on the subject and some recommendations from other participants.

=== CalConnect Interoperability Test Event

Participants in the IOP test events
included Apple, Kerio, Marware, Microsoft, Oracle, RPI (Bedework), Scalix, Sony Ericsson, Sun
Microsystems and Zimbra. Results from the event will be posted at Past IOP Reports as soon as
they are collated and prepared.

=== BOFS

BOF topics included CalDAV Implicit Scheduling, moving forward with a TC-XML, how
to go forward with vCARD, and how to better support and attract European members.

=== New Initiatives

* CalConnect will initiate TC-XML in the area of XML representation of iCalendar data.
* CalConnect will support vCard via existing work within extant TCs plus a coordinating
function in TC CHAIRS, but will not initiate a new TC for vCard at this time. The public
vcard-workshop-l mailing list will be retained as a way of continuing to involve external
participants in ongoing focus in this area.
* CalConnect is exploring offering an invitational "meet CalConnect" event in Europe later
this year as a way to introduce potential members to the Consortium.
* CalConnect has initated a Guest Speaker program to invite selected individuals to speak to
CalConnect who are unlikely to attend Roundtables due to locale or work interests.

== Future Meetings

* ROUNDTABLE XII: June 2-6, 2008, at the University of Wisconsin, Madison, Wisconsin.
* ROUNDTABLE XIII: October 6-10, 2008, at Zimbra, Sunnyvalle, California.
* ROUNDTABLE XIV: February 2-6, 2009, host and location to be determined.

The format of the CalConnect week is:

* Monday morning through Wednesday noon, C.I.T.E. (CalConnect Interoperability Test Events)
* Wednesday noon through Friday afternoon, Roundtable (presentations, TC sessions, BOFs,
networking, Plenary).
