= Report on Roundtable XIII, October 8-10 2008
:docnumber: 0811
:copyright-year: 2008
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2008-10-10
:published-date: 2008-10-10
:technical-committee: CHAIRS
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable XIII took place October 8-10, 2008, hosted by Yahoo!/Zimbra in Santa Clara,
California. The event was attended by 52 people from 19 organizations, including representatives
from two observers (organizations attending a Roundtable to see if they wish to join).

The CalConnect Interoperability Test Event (CITE) was held immediately prior to the Roundtable,
October 6-8. Eleven organizations and 27 people participated in the regular test event, performing
interoperability testing between their calendaring and scheduling implementations. A reports on
the CITE will be published as soon as information has been delivered from all participants.

The Roundtable was dedicated to technical committee sessions, BOFs, and informal discussions
and networking, with an all-hands Plenary meeting as the last item on Friday afternoon. The
Technical Committee sessions were as usual organized sequentially, without competing parallel
sessions, as is our standard practice to allow all attendees who wished to be involved in the
discussions of each Technical Committee the opportunity to do so.

An additional ten invitees joined us for the Technical Previews session on Wednesday afternoon.
The previews demonstrated live interoperability in the areas of CalDAV Scheduling, iSchedule
Server-Server scheduling, and Free/Busy URL. The presentation accompanying the life demos
will be made available shortly on the CalConnect website.

== Update on Technical Committees and Initiatives

=== TC CALDAV

TC CALDAV reported on its work since the last Roundtable and on the status of
the latest scheduling draft, which includes implicit scheduling. A number of issues were raised and
discussed which will be further discussed and resolved in TC calls going forward. Work on
calendar roles will be resumed once the scheduling issues have been resolved.

=== TC EVENTPUB

TC EVENTPUB presented use cases concerning event publication and venue
information, and proposed some solutions. The TC will begin work on a formal proposal.

=== TC FREEBUSY

TC FREEBUSY summarized its work on the FREEBUSY READ URL draft
proposal. The TC will continue work on finalizing the draft and will begin consideration of issues
involving richer Freebusy information and availability/office hours.

=== TC IOPTEST

TC IOPTEST reported on the IOP test event just completed and on plans to start
collecting and reporting on bug and issue information discovered during the IOP tests. The TC
will look into the possiblity of an iCalendar parser to be made availabe on the CalConnect
website. The TC also presented a live demo of the new Virtual Test Lab facility.

=== TC iSCHEDULE

TC iSCHEDULE presented the status of the draft protocol. Much of the
discussion was on URI schemes and security provisions, such as relying on SSL certificates or to
move to S-MIME certificates in the payload rather than the transport layer. The TC will begin
work on the formal protocol.

=== TC MOBILE

TC MOBILE reported on its work since the last Roundtable and presented
feedback from the Open Mobile Alliance Data Synchronization working group on the TC's
recently published work products: Mobile Calendar Interoperability Test Suite V1.1 and Mobile
Recurrence Interoperability Recommendations. Plans for future interoperability testing were
discussed, including the second CalConnect Mobile Calendaring Interoperability Test Event in
Nov 2008 and beta testing of the new CalConnect Virtual Test Labs. It was agreed that the next
work item for the TC will be a "CalDAV considerations for mobile calendaring" paper.

=== TC TIMEZONE

TC TIMEZONE presented work to date on its draft proposal and RFC, and on
tentative plans to offer an open Timezone Workshop at the next Roundtable. The TC will work on
completion of its registry specification RFC and on a CalConnect Proposal for the Timezone
Service.

=== TC USECASE

TC USECASE presented its work on a new Resource Recommendations
document which includes congruences between iCalendar and vCard. The TC will develop a
formal document for publication and will work to provide its recommendations for vCard
extensions to the IETF in time for its November meeting.

=== TC XML

TC XML reported on its work to date in developing a round-trippable transform of
iCalendar data to/from XML, including an outline of what the XML data would look like and a
Relax NG Schema. Going forward the TC will resolve open issues and prepare a formal draft
document.

=== CalConnect Interoperability Test Event

Participants in the IOP test included
Apple, E&S Software, Google, IBM, Kerio, Microsoft, PeopleCube, RPI (Bedework), Scalix, Sun,
and Yahoo!/Zimbra. Results from the event will be posted at Past IOP Reports as soon as they are
collated and prepared.

=== New Initiatives

* The CalConnect Virtual Test Lab will be piloted immediately after Roundtable XIII and
should be available for use by the Mobile IOP Test Event in November.
* The second Mobile Interoperability Test Event will be held on 4-6 November, 2008, in
Plzen, Czech Republic, hosted by Kerio Technologies.
* CalConnect will offer a half-day Meet CalConnect introductory event on November 7 in
Prague, and November 10 in London.
* CalConnect will host an open Timezone Workshop on Tuesday, February 3, during the
CalConnect XIV week in Redmond.

== Future Meetings

* Mobile IOP Test Event: November 4-6, 2008, at Kerio Technologies, Plzen, Czech Republic.
* Meet CalConnect introductory event: November 7 (Prague) and November 10 (London), 2008.
* CALCONNECT XIV: February 2-6, 2009, Microsoft, Redmond, Washington.
* CALCONNECT XV: June 1-5, 2009, host and location TBD.
* CALCONNECT XVI: October 5-9, 2009, host and location TBD.

The format of the CalConnect week is:

* Monday morning through Wednesday noon, C.I.T.E. (CalConnect Interoperability Test Event)
* Wednesday noon through Friday afternoon, Roundtable (presentations, TC sessions, BOFs,
networking, Plenary).
