= Report on Roundtable V, 09-12 January 2006
:docnumber: 0613
:copyright-year: 2006
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2006-01-12
:published-date: 2006-01-12
:technical-committee: CHAIRS
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable V took place on January 9-12, 2006, hosted by Novell in Provo, Utah. Monday
January 9th and Tuesday morning the 10th were a dedicated CalConnect Interoperability Event
where seven organizations performed interoperability testing on their calendaring and scheduling
implementations. The Roundtable itself convened midday on Tuesday the 10th and closed midday
on Thursday the 12th. As usual, most of the time was dedicated to technical committee sessions,
with an all-hands Plenary meeting at the end. The Technical Committee sessions were organized
sequentially, to allow all attendees who wished to be involved in the discussions of a Technical
Committee the opportunity to do so. Delegates were also present from The Open Group
Messaging Forum to discuss a possible joint endeavor with respect to a Federated Freebusy
Challenge which the TOG/MF has issued.

== Update on Technical Committees and Initiatives

*Work Products*: _The iCalendar Timezone Problems and Recommendations_ document and an
update to the _Min-IOP Use Cases_ document were approved for publication and have been
published on the Consortium web site. The _Timezone Registry/Resource Recommendations_
document, _Calendaring Glossary_, and _Recurrence Problems and Recommendations_ document,
among others, are in progress; the Recurrence document is intended to be published in time to be
delivered to the CALSIFY Working Group of the IETF in March.

*TC-AUTHENTICATE* is undertaking a study of authentication schemes used by existing
calendaring and scheduling implementations (many proprietary) in preparation for
recommendations for short-term and longer-term authentication methods for calendaring. The
study will be published when complete.

*TC-CALDAV* is beginning work on use cases and requirements for CalDAV Scheduling as input
to the development of the scheduling draft for CalDAV. The TC is also considering requirements
for a specialized Freebusy Service component for CalDAV which might address the TOG/MF
requirement mentioned above.

*TC-EVENTPUB* has conducted a survey on existing event publication systems, and is working
on requirements for expanded location information in iCalendar to support the needs for event
publication.

*TC-MOBILE* is conducting a survey of calendaring with mobile devices and has begun the
development of a problem statement to define the requirements for open, interoperable
calendaring with mobile devices. The TC hopes to liaise with the OMA in April and invite their
participation in the May Roundtable to assist in developing the requirements for calendaring and
scheduling standards to support mobile devices.

*TC-REALTIME* is beginning the refinement of use cases associated with "real time" server-toserver
communcation.

*TC-RECURR* is in the process of refining its Problems and Recommendations document to be
delivered to the IETF Calsify Working Group in time for their March meeting.

*TC-TIMEZONE* has completed its Problems and Recommendations document for publication
and is working on a Timezone Registry and Service recommendations document.

*TC-USECASE* has completed its Min-IOP Use Cases document for publication and is working on
the Calendaring Glossary document.

*CalConnect Interoperability Event*: Participants in the interoperability testing event included
EVDB, Mozilla, Novell, Oracle, OSAF, RPI (Rensselaer Polytechnic Institute) and Trumba.
Results from the event will be posted at Past IOP Reports.

== Future Meetings

The next meeting (Roundtable VI) will take place 22-25 May 2006, hosted by IBM/Lotus in
Cambridge, Massachusetts. Based on the successful model for Roundtable V, where the
CalConnect Interoperability Event was conducted the first 1.5 days, followed by the Roundtable,
this model will be continued at Roundtable VI.
