= Report on Roundtable XV, June 3-5 2009
:docnumber: 0908
:copyright-year: 2009
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2009-06-11
:published-date: 2009-06-11
:technical-committee: CHAIRS
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable XV took place on June 3-5 2009, hosted by Oracle Corporation in Redwood Shores,
California. The event was attended by 33 people from 20 members, plus a representative from the
OASIS oBIX working group.

The CalConnect Interoperability Test Event (CITE) was held immediately prior to the Roundtable
on June 1-3. Six organizations and 13 people participated in the regular test event, performing
interoperability testing between their calendaring and scheduling implementations. A report on the
CITE will be published as soon as information has been delivered from all participants.

The Roundtable was dedicated to technical committee sessions, and informal discussions and
networking, with an all-hands Plenary meeting as the last item on Friday afternoon. The Technical
Committee sessions were as usual organized sequentially, without competing parallel sessions, as
is our standard practice to allow all attendees who wished to be involved in the discussions of each
Technical Committee the opportunity to do so.

== Special Events

A short (2 hour) workshop was held on Wednesday afternoon on Shared/Group/Public Calendars,
and provided a unique opportunity for discussion of this key area of calendaring that many
participants are interested in. The intent was to identify models and use cases for these types of
calendars and calendaring, what technologies and standards are needed, and how to move forward.
Work items will be picked up by TC USECASE and TC CALDAV to continue this effort.

== Update on Technical Committees and Initiatives

=== TC CALDAV

TC CALDAV provided a status update on the various IETF Internet Drafts
relevant to CalDAV. The ZideOne Outlook to CalDAV connector was demonstrated. An open
discussion was held on several projects for extensions to CalDAV which will be part of the TC's
remit going forward.

=== TC EVENTPUB

TC EVENTPUB discussed the interactions between the TC and the shared
calendar workshop discussions throughout much of the Roundtable, in particular public events use
cases previously developed by the TC. The TC also discussed the state of work in its document
describing how vCard can be used with iCalendar. A decision was made to put the TC on hold
pending completion of vCard 4.0 work in the IETF, when it can be integrated into the
EVENTPUB resource proposal.

=== TC FREEBUSY

TC FREEBUSY reviewed the publication of the Freebusy Read URL proposal
and discussed work that has begun on a proposal for support of consensus scheduling.

=== TC IOPTEST

TC IOPTEST reported on the IOP test event just completed (elsewhere in this
report) and on plans for an iCalendar parser and further use of the Virtual Test Lab Facility. The
TC expects that testing will begin in October in new areas such as Freebusy Read URL, CardDAV,
and the new Timezone service and registry proposals (the first two were tested informally this
time; the Timezone protocols may begin informal testing in October).

=== TC iSCHEDULE

TC iSCHEDULE discussed the progress on the protocol and had an open
discussion on methods of deploying the iSchedule protocol in various scenarios.

=== TC MOBILE

TC MOBILE discussed its work on a Vision for Mobile Calendar, and held an
open discussion on the use cases for the document. An agreement was reached on the desirability
of a proposed document describing how CalDAV could effectively be used by mobile devices. The
Technical Committee is looking for a new Chair, following the reassignment of the previous Chair
within his organization.

=== TC RESOURCE

TC RESOURCE was established after the last Roundtable and has begun work
on defining a schema to represent resource attributes to enhance interoperability of resource data.
A consensus was reached in the discussion to use an abstract schema a bit more complicated than
name-value pairs, with an LDAP mapping example at the end of the document.

=== TC TIMEZONE

TC TIMEZONE presented work to date on its draft RFCs on Timezone
Registry and Timezone Service. It seems likely that there will be at least three trial
implementations available for interoperability testing at the October C.I.T.E.

=== TC USECASE

TC USECASE presented an overview of its three Resouce documents which
have just completed Last Call, and a vote to publish was taken at the TC Wrapup session at the
end of Roundtable XV. The documents are published at:

* State of Resource Interoperability for Calendaring, Groupware, and Project Management
* Use Cases for Resources V1.0
* A Recommendation for Minimum Interoperability of Resource Information

The TC will begin work in three areas new areas:

* Use cases for non-institutional, non-enterprise calendar users.
* Use cases drawn from the Shared Calendar Workshop notes.
* A revision of the Calendaring and Scheduling Glossary of Terms.

=== TC XML

The protocol for a round-trippable transform of iCalendar data to/from XML has been
completed and approved for publication, and has been submitted to the IETF as an Internet Draft;
see iCalendar XML Representation. A visitor from the OASIS oBIX working group was present
and discussed their interest in taking advantage of this work in the devleopment of their WS
calendar specification for intelligent building management. TX XML expects to begin next on a
JSON document for the specification.

== CalConnect Interoperability Test Event

Participants in the IOP test included Apple, Microsoft, Oracle, PeopleCube, Rensselaer
Polytechnic Institute (Bedework), and ZideOne. In addition to regular CalDAV, iMIP and iTIP
testing, some informal CardDAV and Freebusy Read URL testing was done as well. Results from
the event will be posted at Past IOP Reports as soon as they are collated and prepared.

== Future Events

* CALCONNECT XVI: October 5-9, 2009, hosted by Apple in Cupertino, California
* CALCONNECT XVII: February 1-5, 2010, hosted by the University of California, Irvine, in
Irvine, Californa

The format of the CalConnect week is:

* Monday morning through Wednesday noon, C.I.T.E. (CalConnect Interoperability Test Event)
* Wednesday noon through Friday afternoon, Roundtable (presentations, TC sessions, BOFs,
networking, Plenary).
