= Report on Roundtable XIV, February 4-6 2009
:docnumber: 0901
:copyright-year: 2009
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2009-02-06
:published-date: 2009-02-06
:technical-committee: CHAIRS
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable XIV took place on February 4-6, 2009, hosted by Microsoft in Redmond, Washington.
The event was attended by 31 people from 20 organizations, including representatives from two
observers (organizations attending a Roundtable to see if they wish to join).

The CalConnect Interoperability Test Event (CITE) was held immediately prior to the Roundtable
on February 2-4. Five organizations and 18 people participated in the regular test event,
performing interoperability testing between their calendaring and scheduling implementations. A
reports on the CITE will be published as soon as information has been delivered from all
participants.

The Roundtable was dedicated to technical committee sessions, BOFs, and informal discussions
and networking, with an all-hands Plenary meeting as the last item on Friday afternoon. The
Technical Committee sessions were as usual organized sequentially, without competing parallel
sessions, as is our standard practice to allow all attendees who wished to be involved in the
discussions of each Technical Committee the opportunity to do so.

== Special Events

Two special events occured at this roundtable. On Tuesday, the Timezone Technical Committee
sponsored an open workshop on issues with timezones, and CalConnect's work towards a
Timezone Registry and Timezone Service proposals. The event was attended by 17 people; remote
call-in and Livemeeting support was also available.

On Wednesday afternoon Ben Fortuna, the author of iCal4J, was our first guest speaker. Ben spoke
about the inception and evolution of ical4j, and where he saw ical4j going in the future. Ben was
with us almost the entire week, so the membership had many opportunities to meet and talk with
Ben. Ben's presentation may be found at iCal4j at CalConnect.

== Update on Technical Committees and Initiatives

The following documents are about to finish Last Call and be published:

* The draft proposed RFC for the iCalendar<-->XML transformation specification from TC
XML
* The Freebusy Read URL draft proposed RFC from TC FREEBUSY
* The draft RESOURCE proposed RFC from TC EVENTPUB

The Calendar Standards Roadmap, which originally came out of TC-CalDAV, was enthusiastically
discussed at this Roundtable, spawning work in new areas by several TC's. This discussion is
hopefully just the beginning of a longer, engaging conversation.

Calonnect and the World Wide Calendar: This brainstorming session for everyone attending the
Roundtable was designed to get people's heads up and have them look at the larger picture. We
looked at calendaring issues beyond the institutions and corporations most of us represent.
Interoperability on a world wide scale will begin to happen when soccer moms (or football
mums!) can see when their child's next game is and make appointments with their doctor as easily
as keep a work schedule. We discussed social adaptations like ubiquitous cell phone conversations
(maybe not a plus!) as well as the coming integration of calendaring with social networking sites
like Facebook. We intend for this to be an ongoing discussions at Roundtables as we pull back
from the (equally important) technical work to view calendaring from the viewpoint of the world
at large.

== CalConnect Interoperability Test Event

Participants in the IOP test included Apple, IBM, Microsoft, PeopleCube, and Yahoo!/Zimbra.
Results from the event will be posted at Past IOP Reports as soon as they are collated and
prepared.

== Other Events

* The second Mobile Interoperability Test Event was be held on 4-6 November, 2008, in
Plzen, Czech Republic, hosted by Kerio Technologies. The report from this IOP Test Event
may be found at Mobile Calendaring IOP Test Event Report - Nov 2008.
* CalConnect offered a half-day "Meet CalConnect" introductory event on November 7 in
Prague, and November 10 in London. A zip file of most of the presentations may be found
at Meet CalConnect Presentations.

== Future Events

* CALCONNECT XV: June 1-5, 2009.
* CALCONNECT XVI: October 5-9, 2009
* CALCONNECT XVII: February 1-5, 2010
* Third Mobile Calendaring IOP Test Event: timing and location not yet determined

The format of the CalConnect week is:

* Monday morning through Wednesday noon, C.I.T.E. (CalConnect Interoperability Test Event)
* Wednesday noon through Friday afternoon, Roundtable (presentations, TC sessions, BOFs,
networking, Plenary).
