= Report on Roundtable IX, May 7-11 2007
:docnumber: 0712
:copyright-year: 2007
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2007-05-11
:published-date: 2007-05-11
:technical-committee: CHAIRS
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable IX and the accompanying IOP test event took place May 7-11, 2007, hosted by Boeing
in Seattle, Washington. The event was attended by 43 representatives from 31 organizations,
including representatives from three observers (organizations attending a Roundtable to see if they
wish to join).

Monday noon through Wednesday noon, May 7-9, was a dedicated CalConnect Interoperability
Test Event where 6 participating organizations performed interoperability testing between their
calendaring and scheduling implementations. Wednesday afternoon, all day Thursday, and Friday
morning comprised the Roundtable. The majority of this time was dedicated to technical
committee sessions, BOFs, and informal discussions and networking, with an all-hands Plenary
meeting as the last item on Friday morning. The Technical Committee sessions were organized
sequentially, to allow all attendees who wished to be involved in the discussions of a Technical
Committee the opportunity to do so.

== Update on Technical Committees and Initiatives

=== Work Products

Since Roundtable VIII, TC USECASE has published the Minimum
Interoperable Subset Use Cases for Tasks (VTODO), and the DST Ad Hoc committee regularly
updated the Extended Daylight Savings Time Information pages to provide information on the
early shift to Daylight Savings Time. The Consortium also implemented a public Calendar
Administrators Discussion List, and a new website.

=== TC CALDAV

The TC is in the final stages of work on the _CalDAV Scheduling Requirements_
paper which should be published in June. The TC also has several extensions which have been
proposed for investigation, but expects to complete its work by Roundtable X in September.

=== TC EVENTPUB

TC EVENTPUB reviewed VVENUE and discussions on localization, and the
current status of work on the "eventmap" event sharing proposal.

=== TC FREEBUSY

TC FREEBUSY reviewed previous work including the status of the Boeing
Federated Free/Busy project, and has begun work on the FREEBUSY URL proposal.

=== TC IOPTEST

TC IOPTEST initiated monthly Jabber IOP test events as an adjunct to the full
IOP test events held with Roundtables. The TC reported on the IOP test event just completed, and
is continuing to work with TC MOBILE on the development of a Mobile Interoperability Test
Suite and planning for a Mobile Interoperability Test Event.

=== TC MOBILE

TC MOBILE reviewed the current draft of its Mobile Interoperability Test Suite,
and continues to develop it. The TC plans a Mobile Interoperability Test Event targeted to the
mobile industry in 4Q07 or 1Q08, probably in the U.K. or Europe. The TC is also working on
recurrence simplification for mobile devices as input to the IETF CALSIFY effort.

=== TC REALTIME

The TC will be reactivated in June and expects to begin work with the
consideration of Anonymous Free/Busy, in conjunction with TC FREEBUSY.

=== TC USECASE

The TC has published the Min-IOP (Minimum Interoperable Subset) Use Cases
for Tasks (VTODO) and has begun work on considering Use Cases for Resources. The TC has
also undertaken a study of recurrence features in mobile device support for TC MOBILE.

=== Daylight Saving Time Ad Hoc

The DST Ad Hoc reported on its work leading up th the DST
conversion in March, and plans to prepare a "lessons learned" document. The document will cover
preparations, lessons learned, planning for November, and longer-term recommendations.

=== CalConnect Interoperability Test Event

Participants in the IOP test event
included Apple, Marware, OSAF, Bedework (Rensselaer Polytechnic Institute) Sun Microsystems
(Lightning), and Synchronica. Results from the event will be posted at Past IOP Reports as soon
as they are collated and prepared.

=== BOFS

BOF topics included SSE (Simple Sharing Extensions), XML for iCalendar representation,
vCard initiatives, and the DST follow-on work.

=== New Initiatives

The Consortium plans to initiate work on a follow-on activity to TC
TIMEZONE in the area of a timezone registry and service protocol; XML for iCalendar
representation; and a possible vCard/Content Workshop in September to help define the problems
and potential solutions.

== Future Meetings

* ROUNDTABLE X: September 17-21, Cambridge, Massachusetts, hosted by M.I.T. (location and
host tentative).
* ROUNDTABLE XI: February 4-8, 2008, location and host TBD
* ROUNDTABLE XII: June 2-6, 2008, Madison, Wisconsin, hosted by the University of
Wisconsin (date, location and host tentative).

The format of CalConnect week will remain the same for these events:

* Monday noon through Wednesday noon, IOP Test Event
* Wednesday noon through Friday noon, Roundtable (TC sessions, BOFs, networking, Plenary).
