= Report on Roundtable XXV, October 3-5, 2012
:docnumber: 1204
:copyright-year: 2012
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2012-10-18
:published-date: 2012-10-18
:technical-committee: CHAIRS
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable XXV took place on October 3-5, 2012, hosted by Google in Zürich, Switzerland. The event
was attended by 26 people from 11 members and 5 non-members. The CalConnect Interoperability Test
Event was held immediately prior to the Roundtable on October 1-3. Twenty-two people from 10 members
and 2 non-members were present onsite, and four members participated remotely.

The Roundtable was dedicated to technical committee sessions, and informal discussions and networking,
with an all-hands Plenary meeting as the last item on Friday afternoon. The Technical Committee sessions
were as usual organized sequentially, without competing parallel sessions, as is our standard practice to
allow all attendees who wished to be involved in the discussions of each Technical Committee the
opportunity to do so.

== Special Events

The Roundtable was structured with all regular TC sessions occurring in the afternoon to facilitate remote
participation (in particular from North America) for the TC sessions. Thursday and Friday mornings were
used for special symposia and BOFs:

* Improving the web calendaring experience for end users
* Calendaring futures and CalConnect directions
* Internationalization/Localization for calendaring data
* Best practices for publishing iCalendar data to ensure optimum interoperability
* BOF on VTODOs
* BOF on Consensus Scheduling

Following the BOF on VTODOs, a VTODO Ad Hoc Committee was formed to examine requirements and
ongooing work on VTODOs and recommend future activity in this area to CalConnect. The Ad Hoc
committee will report out at Roundtable XXVI.

The host session was presented by Fabian Schlup of Google and focused on various aspects of Google
Calendar including internal and external APIs.

== Documents since Last Roundtable

Public Review Documents:

* CalWS-SOAP SOAP Web Services Protocol for Calendaring

Updated IETF Drafts and Proposed Standards (published RFCs) related to CalConnect (includes updates
to published CalConnect documents):

NOTE: The majority of specification work in CalConnect is necessarily focused on work to become internet draft
submissions to the IETF and ultimpately be progressed to become RFCs (Proposed Standards), rather
than be directly published by CalConnect itself.

* https://tools.ietf.org/html/draft-daboo-calendar-availability-03
* https://tools.ietf.org/html/draft-daboo-icalendar-extensions-05
* https://datatracker.ietf.org/doc/draft-daboo-ical-vcard-parameter-encoding/
* https://tools.ietf.org/html/draft-daboo-valarm-extensions-04
* https://www.ietf.org/rfc/rfc6638.txt[Scheduling Extensions to CalDAV RFC 6638]
* http://svn.calendarserver.org/repository/calendarserver/CalendarServer/trunk/doc/Extensions/caldavsharing.txt
* https://tools.ietf.org/html/draft-daboo-ical-vcard-parameter-encoding-01
* https://datatracker.ietf.org/doc/draft-murchison-webdav-prefer/
* https://datatracker.ietf.org/doc/draft-daboo-aggregated-service-discovery/

CalConnect has replaced the internal Interoperability Test Event Report with an internal wiki and
etherpads, and the public Interoperability Test Report with a section on the Test Event in the CalConnect
_Minutes_ newsletter publised after each event.

== Update on Technical Committee Work and Initiatives

Roundtable session summaries and activities and a report on the Interoperability Test Event are published
after each CalConnect event as part of the CalConnect _Minutes_ newsletter, to be published shortly. Issues
of the newsletter may be found at CalConnect _Minutes_.

== Future Events

* CalConnect XXVI: January 28 - February 1, 2013, Oracle, San Francisco Bay Area, California
* CalConnect XXVII: June 3-7, 2013, University of Wisconsin, Madison, Wisconsin
* CalConnect XVIII: Autumn, 2013 (late September/early October), TBD

The general format of the CalConnect week is:

* Monday morning through Wednesday noon, CalConnect Interoperability Test Event
* Wednesday noon through Friday afternoon, CalConnect Roundtable (presentations, TC sessions, BOFs,
networking, Plenary)

This format has been altered for the two (so far) European CalConnect events to move all TC sessions to
the afternoon and offer symposia and BOFs during Thursday and Friday mornings.
