= Report on Roundtable XII, June 4-6 2008
:docnumber: 0810
:copyright-year: 2008
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2008-06-06
:published-date: 2008-06-06
:technical-committee: CHAIRS
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

Roundtable XII took place June 4-6, 2008, hosted by the University of Wisconsin in Madison,
Wisconsin. The event was attended by 31 people from 22 organizations, including representatives
from two observers (organizations attending a Roundtable to see if they wish to join).

The Roundtable was dedicated to technical committee sessions, BOFs, and informal discussions
and networking, with an all-hands Plenary meeting as the last item on Friday afternoon. The
Technical Committee sessions were as usual organized sequentially, without competing parallel
sessions, as is our standard practice to allow all attendees who wished to be involved in the
discussions of each Technical Committee the opportunity to do so.

== Update on Technical Committees and Initiatives

=== TC CALDAV

TC CALDAV reported on its work since the last Roundtable and on implicit
scheduling. In particular the discussion focused on calendar roles in preparation for the
development of a draft protocol on role-based access control in CalDAV.

=== TC EVENTPUB

TC EVENTPUB discussed venue information on vCard and the need to let the
new vCard specification develop. vCard V4 as planned will include new property types for
individual, organization, and group, and provide scope for resources. The TC will focus going
forward on requirements and use cases around the public event space, and additionally on how
that may relate to CalDAV.

=== TC FREEBUSY

TC FREEBUSY reviewed its work on Freebusy URL. Key issues related to
whether FBURL would be used to publish information, as well as meeting events and interactions
with CalDAV. Going forward the TC will focus on developing a formal FBURL specification.

=== TC IOPTEST

TC IOPTEST reported on the IOP test event just completed, and presented the
proposed Virtual Test Lab as part of the TC MOBILE session.

=== TC MOBILE

TC MOBILE presented its work on extending the Mobile Calendar
Interoperability Test Suite in the area of recurrences and formal definitions of mobile device
capability levels. Plans for a Virtual Test Lab were presented by TC IOPTEST, and the second
Mobile Interoperability Test Event was decided upon.

=== TC TIMEZONE

TC TIMEZONE presented the work to date on its draft proposal and RFC and
will work towards having the proposal ready to present at the October Roundtable.

=== TC USECASE

TC USECASE has been reviewing the topic of resources and finds little
commonality between existing implementations. The TC will focus on a recommendation
document for specific resource management issues.

=== TC XML

TC XML, founded at the last Roundtable, reported on its work to date in developing a
transform of iCalendar data to/from XML, particularly with respect to the size of an XML
representation and the relative friendliness of the XML created.

=== CalConnect Interoperability Test Event

Participants in the IOP test included
Apple, Mozilla, RPI (Bedework), Scalix, and Yahoo!/Zimbra. Results from the event will be
posted at Past IOP Reports as soon as they are collated and prepared.

=== BOFS

The major BOF was on preparing for an enhanced Technology Preview at the October
event, and to what degree CalConnect should be trying to conduct a public event with press
representatives. As before, we will invite a small number of selected individuals from the media
with an interest in calendaring to the Technical Preview in October.

=== New Initiatives

* CalConnect is developing a pilot of a Virtual Test Lab, to allow remote interoperability
testing of regular or mobile calendaring between registered test pairs, as an adjunct to its
regular in-person IOP test events.
* The second Mobile Interoperability Test Event will be held on 4-6 November, 2008, in
Plzen, Czech Republic, hosted by Kerio Technologies.
* CalConnect is continuing to consider an invitational "meet CalConnect" event in Europe but
the location and timing is still under discussion.

== Future Meetings

* ROUNDTABLE XIII: October 6-10, 2008, at Yahoo!, Sunnyvale, California.
Mobile IOP Test Event: November 4-6, 2008, at Kerio Technologies, Plzen, Czech Republic.
* ROUNDTABLE XIV: February 2-6, 2009, host and location TBD (east coast intended).
* ROUNDTABLE XV: June 1-5, 2009, host and location TBD (west coast intended).

The format of the CalConnect week is:

* Monday morning through Wednesday noon, C.I.T.E. (CalConnect Interoperability Test Event)
* Wednesday noon through Friday afternoon, Roundtable (presentations, TC sessions, BOFs,
networking, Plenary).
