= Report on Interoperability Test Event XXXI, September 29 - October 1, 2014
:docnumber: 1407
:copyright-year: 2014
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2014-10-31
:published-date: 2014-10-31
:technical-committee: IOPTEST
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:


.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Report

The interoperability test event at CalConnect XXXI, hosted by Youcanbook.me in Bedford,
United Kingdom took place on Monday September 29 through Wednesday noon October 1.

There were 10 members participating onsite represented by 14 individuals. In addition two
members participated remotely. Participating entities and primary testing interests were:

* 1and1 - basic CalDAV testing
* Apple - Calendar Server: timezone distribution, VPOLL and iSchedule; IOS8
* Bedework - VPOLL and timezone distribution
* CMU - VPOLL and iSchedule
* fruux - SabreDAV
* Helge Hess - individual testing support
* Mozilla - Lightning CalDAV, jCal and jCard
* SmoothSync - CalDAVSync and CardDAVsync, General CalDAV and CardDAV, service
discovery
* Youcanbook.me - Google Calendar and general CalDAV
* Zimbra - CalDAV auto scheduling

As always, many were testing basic CalDAV features with some starting to test their
implementations of CalDAV implicit scheduling. A number of errors were found and fixed and in
some cases discussions resolved misunderstandings of the protocols.

Three of the server implementations attempted to set up a demonstration of a combination of
VPOLL, iSchedule and jCal between them. Ultimately this wasn't achieved - mostly due to the
problems of setting up remore servers with certificates and getting DKIM to work correctly. There
were changes to all servers as a result and there was a local demonstration of the current state of
the Bedework VPOLL client during the TC FREEBUSY session. We hope to have a full working
demonstration with multiple servers by CalConnect XXXII.

The testing was fairly intensive after the initial pairing off. Testers were busy throughout the
event.

Once again we had some BOF sessions -- this time we discussed the issues around task assignment
in VPOLL and providing server information to clients as a fetchable document. These discussions,
usually at the developer and implementor level, have become a valuable part of the experience.

Many thanks to Youcanbookme for hosting this event. The configuration of the room and
networks gave no trouble allowing all participants to make an immediate start. The catering for
this event was excellent.

Mike Douglass, CalConnect Interoperability Test Manager
