= Report on Roundtable II, 11-13 January 2005
:docnumber: 0511
:copyright-year: 2005
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2005-01-13
:published-date: 2005-01-13
:technical-committee: CALCONNECT
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Introduction

The first post-launch event of The Calendaring and Scheduling Consortium took place on 11-13
January, 2005, sponsored by the University of Washington in Seattle. The event was attended by
31 people representing 16 organizations. The Roundtable event consisted of two days of Technical
Committee meetings, followed by an all-hands plenary meeting of the membership and attendees.
The first two days, a CalConnect Interoperability Event was held in parallel with the Technical
Committee meetings. The Technical Committee sessions were organized sequentially, to allow all
attendees who wished to be involved in the discussions of a Technical Committee the opportunity
to do so, and there was definitely "drift" between TC sessions and those participating in the
CalConnect Interoperability Event.

== New Initiatives

*TC-TIMEZONE* was formed as a result of work being done in CalDAV showing the need for a
formal time zone registry; iCAL needs this as well. Some work has been done in the past in this
area; the new Technical Committee will gather the work that has been done and develop a
proposal as to how best to move this forward.

*TC-EVENTPUB* was formed based on work being done at UC Berkeley and elsewhere to
develop a precise understanding of event publishing and how it differs from general scheduling
problems, with the goal of attracting efforts being done in several academic institutions and
elsewhere to combine into a single work project and Technical Committee within Calconnect.

*TC-CALSIFY* was re chartered with an expanded scope to support and help drive the CALSIFY
effort in the IETF via a Working Group to consider the potential revision of RFC 2445.

*Glossary Project*: The work done in the USECASE Technical Committee has shown the need for
a taxonomy document for common vocabulary and glossary for calendaring and scheduling. Ms.
Egan volunteered to act as Project Editor to compile a first draft document for circulation by mid-
February. The Glossary, once complete, will be posted and publicly available on the Calconnect
website.

*External Communications*: The Consortium has chartered an ad hoc group to develop proposals
for publicity, promotion, and recruitment, e.g. ways of communicating activities in calendaring
and scheduling, such as an RSS Feed for the C&S space, speaking appearances at technical
conferences and trade shows, and an expanded website presence including links to sites offering
calendaring functionality.

== Calconnect Interoperability Event

Participants in the CalConnect Interoperability Event included Isamet, Mozilla, Oracle, and the
University of Washington. The major part of the CalConnect Interoperability Event was CalDAV
testing; this was the first formal interoperability testing of CalDAV implementations, and
demonstrated basic interoperability between two CalDAV servers (Isamet, Oracle) and three
clients (Isamet Mulberry Desktop and Mobile Clients and Mozilla). The results of the CalConnect
Interoperability Event should be available by early February and will be posted on the Consortium
website and delivered to the IETF.

== Technical Committees

Five Technical Committees met on Tuesday and Wednesday.

The Min-IOP Technical Committee is working to develop a comprehensive table of which features
of iCAL are actually implemented in which Calendaring products and are able to interoperate
successfully. The goal is to determine the minimum interoperable subset of functions defined by
the three RFCs which are actually in use and which must be succesfully carried forward into any
revision or "simplification" of RFC 2445, iCalendar. The Technical Committee is actively
involved in developing this matrix and determining how well the matrix maps to what the needed
minimum actually is.

The CALDAV Technical Committee will produce scenarios for additional CalDAV testing for the
next Calconnect Interoperability Event, then turn to assisting CalDAV authors in submitting the
CalDAV draft to the IETF. They expect to use the use cases from the USECASE TC and anticipate
contributing additional use cases. CALDAV is very interested in being able to conduct virtual
Interops on a monthly basis and will work with IOP/TEST and the IOP Manager to accomplish
this under Consortium auspices. The Oracle and Isamet CalDAV servers are available on the
internet for client testing.

The CALDAV participants were heavily involved in the CalConnect Interoperability Event and
also provided several demonstrations to the Roundtable:

* Mozilla's Sunbird and Oracle Calendar with CalDAV protocol adapter
* Mozilla's Sunbird and Oracle's Exchange CalDAV protocol adapter
* Isamet Mulberry Desktop Client and Isamet CalDAV server
* Isamet Mulberry Mobile Client and Isamet CalDAV server

The IOP/TEST Technical Committee is working to develop and formalize the Consortium's
CalConnect Interoperability Event testing. Among the issues being addressed by the Technical
Committee are planning and implementing virtual and ad hoc interops; how to contact nonmembers
about CalConnect Interoperability Event testing; how to establish CalConnect
Interoperability Event planning early on and integrate product planning; and how to conduct
multiple CalConnect Interoperability Event tests together. The Committee is also beginning
discussions on a reference implementations which for ad hoc testing by implementers as a service
from the Consortium to promote calendaring and scheduling standards.

The RECURR Technical Committee was only able to meet briefly as the Chair was not able to
come to the Roundtable and had to join the TC by teleconference. The problem statement for the
TC was reviewed and narrowed to focus on recurrence rule problems. An additional effort will be
to identify and document the specifics of existing problems with recurrence rules as part of the
MIN-IOP effort.

The USECASE Technical Committee spent substantial time compiling a set of Use Cases
identifying "real world" requirements for interoperable calendaring and scheduling
implementations. Some 29 specific use cases were documented. The next steps will be to develop
a ranking method and continue to add use cases from other members, and from other Technical
Committees.

== Future Meetings

Three regular meetings per year were agreed, roughly in January, May, and September. The
membership is strongly in favor of holding combined 2-1/2 day events featuring a CalConnect
Interoperability Event, Technical Committee meetings, and a membership plenary, after the model
followed at this Roundtable. The Consortium will attempt to alternate meetings between the east
and west coasts. The next meeting (Roundtable III) will take place 1-3 June, 2005, hosted by Duke
University in Durham, North Carolina. The following meeting will be in mid- to late September,
on the west coast.
