name: docker

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Bundler install
        uses: metanorma/ci/docker-gem-install@main

      - name: Print Metanorma version
        run: metanorma --version

      - name: Generate Metanorma XML
        uses: actions-mn/build-and-publish@v2
        with:
          destination: artifact
          artifact-name: mn
          agree-to-terms: true

  fl-build:
    runs-on: ubuntu-latest
    needs: build
    name: Build Firelight version

    steps:
      - name: Download Metanorma artifacts
        uses: actions/download-artifact@v4
        with:
          name: mn
          path: _site

      - name: "Firelight: create temporary Git repo"
        run: |
          git config --global user.email "57123902+metanorma-ci@users.noreply.github.com"
          git config --global user.name "Metanorma CI"
          git config --global init.defaultBranch main
          git init .

      - name: "Firelight: commit"
        run: |
          ls -Al _site/documents/cc-0001-report-ioptest
          git add _site/documents.xml
          git add _site/**/*.pdf
          git add _site/**/*.xml
          git commit -m "Commit MN XML & PDF artifacts"

      - name: "Firelight: prepare config"
        run: |
          cat <<'EOF' >> anafero-config.json
          {
            "version": "0.1",
            "entryPoint": "file:_site/documents.xml",
            "storeAdapters": [
              "git+https://github.com/metanorma/firelight#collection-support/packages/relaton-collection-xml-store",
              "git+https://github.com/metanorma/firelight#collection-support/packages/metanorma-xml-store"
            ],
            "contentAdapters": [
              "git+https://github.com/metanorma/firelight#collection-support/packages/metanorma-site-content"
            ],
            "resourceLayouts": [
              "git+https://github.com/metanorma/firelight#collection-support/packages/plateau-layout"
            ]
          }
          EOF
          git add anafero-config.json
          git commit -m "Add build config"

      - name: "Firelight: generate HTML"
        run: |
          npx --node-options='--experimental-vm-modules' \
            -y @riboseinc/anafero-cli@0.0.43 \
            --target-dir dist \
            --path-prefix /cc-admin-documents \
            --current-rev main

      - uses: actions/upload-artifact@v4
        with:
          name: fl
          path: dist
          if-no-files-found: error

  deploy:
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: fl-build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Make dist dir
        run: mkdir dist

      - name: Download HTML artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: fl
          path: dist

      - name: List files in dist
        run: ls -l dist

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
