= Report on Interoperability Test Event XXXIII, May 18-20, 2015
:docnumber: 1504
:copyright-year: 2015
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2015-06-23
:published-date: 2015-06-23
:technical-committee: IOPTEST
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:


.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Report

The interoperability test event at CalConnect I, hosted by 1&1 in their Bucharest, Romania office,
took place on Monday May 18 through Wednesday noon May 20. The facilities were excellent
and allowed all participants to begin testing immediately.

There were 6 members participating onsite represented by 12 individuals. Participating entities
were:

* 1&1 (the hosts)
* Apple
* fruux
* Google
* RPI (Bedework)
* YouCanBook.me

As is usual we spent some time on discussions - during the interoperability event these are often of
a more technical and protocol oriented nature. These can involve the group as a whole or take the
form of small break out discussions with a subset of the attendees. A brief discussion on API
issues led to the decision that Evert Pot of fruux would produce some proposals for us to look at
during the conference.

Following on from some previous testing there was a discussion on iMIP issues. Cyrus Daboo of
Apple talked about his proposed mail header to identify calendar content in mail messages.

There were also some discussions about the overall approach of CardDAV and in particular how to
implement groups and how this would affect sharing. There was also some discussion about the
CardDAV tests available in the Darwin calendar server test suite.

YouCanBook.me felt this was "a really valuable session of testing". Their service effectively acts
as a client to a number of online calendar services and they carried out a significant amount of
testing against those services. In particular they were carrying out final testing of their new
CalDAV link which is now working well with fruux, iCloud and 1&1. Additionally:

* They improved their detection of the primary calendar status through CalDAV and are now
filtering out non-`VEVENT` calendar collections properly
* They fixed a number of URL illegal character bugs and worked with fruux to signal their
fruux interface
* They tuned the `PROPFIND` calls for 1&1 and identified a missing slash issue
* They built a new link through to iCloud and logged a bug to do with descriptions on
`MKCALENDAR` calls

The other big step forward for YouCanBook.me was talking to everyone about the main status
property at the `VEVENT` level - in particular for "tentative" status. This is something they hope to
use, but need more support from clients. They expect to file bug reports or feature requests on this
topic in the coming months. This, of course, is a feature which will be of use to many others.

As always, the result for many of the server developers were a number of bug fixes.

Mike Douglass, CalConnect Interoperability Test Manager
